// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stopped } = require('../../tools/java-harness')

describe('vanilla recordings: auto_jump', () => {
  recorded('x_autojump_block', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 10, pos: [2.399600454447249, 101.41999998688698, 1381.5], vel: [0.11758154782898447, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 15, pos: [3.151805025123853, 102.25220334025373, 1381.5] },
          'lands (1)': { tick: 18, pos: [3.667426666908207, 102, 1381.5], onGround: true },
          'top speed 5.166 b/s': { tick: 19, pos: [3.9257038917804383, 102, 1381.5], vel: [0.14101938116000978, -0.0784000015258789, 0] },
          'leaves the ground (2)': { tick: 31, pos: [6.566990822235111, 101.92159999847412, 1381.5], vel: [0.11787532265421767, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 35, pos: [7.157712200132851, 101, 1381.5], onGround: true },
          'final state': { tick: 50, pos: [8.548434320706237, 101, 1381.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_block_sprint', {
    description: 'steps: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 7, pos: [2.331717692247412, 101.41999998688698, 1381.5], vel: [0.26020037075381647, 0.33319999363422365, 0], onGround: false },
          'top speed 9.531 b/s': { tick: 7, pos: [2.331717692247412, 101.41999998688698, 1381.5], vel: [0.26020037075381647, 0.33319999363422365, 0] },
          'peak height 1.252': { tick: 12, pos: [3.7580061837051684, 102.25220334025373, 1381.5] },
          'lands (1)': { tick: 15, pos: [4.611729608807088, 102, 1381.5], onGround: true },
          'leaves the ground (2)': { tick: 22, pos: [6.80533059142686, 101.92159999847412, 1381.5], vel: [0.15474473150415285, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 26, pos: [7.578529668180318, 101, 1381.5], onGround: true },
          'final state': { tick: 40, pos: [9.108082554338374, 101, 1381.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_chest', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 10, pos: [2.399600454447249, 101.41999998688698, 1377.5], vel: [0.11758154782898447, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 15, pos: [3.151805025123853, 102.25220334025373, 1377.5] },
          'lands (1)': { tick: 18, pos: [3.667426666908207, 101.875, 1377.5], onGround: true },
          'top speed 5.166 b/s': { tick: 19, pos: [3.9257038917804383, 101.875, 1377.5], vel: [0.14101938116000978, -0.0784000015258789, 0] },
          'leaves the ground (2)': { tick: 31, pos: [6.566990822235111, 101.79659999847412, 1377.5], vel: [0.11787532265421767, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 35, pos: [7.157712200132851, 101, 1377.5], onGround: true },
          'final state': { tick: 50, pos: [8.548434320706237, 101, 1377.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_fence', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.316 b/s': { tick: 13, pos: [3.0466658857048783, 101, 1433.5], vel: [0.11781389317747222, -0.0784000015258789, 0] },
          'touches a wall': { tick: 14, pos: [3.074999988079071, 101, 1433.5], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [3.074999988079071, 101, 1433.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_slab', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.5': { tick: 12, pos: [2.830889549636968, 101.5, 1329.5] },
          'leaves the ground (1)': { tick: 30, pos: [6.716170554523109, 101.42159999847412, 1329.5], vel: [0.11785906350182895, -0.1552320045166016, 0], onGround: false },
          'lands (1)': { tick: 33, pos: [7.149583226657798, 101, 1329.5], onGround: true },
          'top speed 4.713 b/s': { tick: 34, pos: [7.385235164231994, 101, 1329.5], vel: [0.12866597286040174, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [8.960030318863181, 101, 1329.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_sneaking', {
    description: 'steps: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1381.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'touches a wall': { tick: 33, pos: [2.699999988079071, 101, 1381.5], isCollidedHorizontally: true },
          'final state': { tick: 63, pos: [2.699999988079071, 101, 1381.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
