// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stopped } = require('../../tools/java-harness')

describe('vanilla recordings: auto_jump', () => {
  recorded('x_autojump_block', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1381.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1381.5], onGround: true },
          'leaves the ground (2)': { tick: 11, pos: [2.5012638199911734, 101.41999998688698, 1381.5], vel: [0.11763769845470062, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 16, pos: [3.2537029554611583, 102.25220334025373, 1381.5] },
          'lands (2)': { tick: 19, pos: [3.7694205397257523, 102, 1381.5], onGround: true },
          'top speed 5.166 b/s': { tick: 20, pos: [4.027724169577741, 102, 1381.5], vel: [0.14103379828063228, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [8.434594850021233, 101, 1381.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_block_sprint', {
    description: 'steps: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.6274000124096872, 101, 1381.5], vel: [0.0695604148553142, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.7224404264612327, 101, 1381.5], onGround: true },
          'leaves the ground (2)': { tick: 8, pos: [2.4630530638292196, 101.41999998688698, 1381.5], vel: [0.2606488267610062, 0.33319999363422365, 0], onGround: false },
          'top speed 9.548 b/s': { tick: 8, pos: [2.4630530638292196, 101.41999998688698, 1381.5], vel: [0.2606488267610062, 0.33319999363422365, 0] },
          'touches a wall': { tick: 9, pos: [2.699999988079071, 101.7531999805212, 1381.5], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 13, pos: [2.932881351910028, 102.25220334025373, 1381.5] },
          'lands (2)': { tick: 16, pos: [3.298473382222989, 102, 1381.5], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_chest', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1377.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1377.5], onGround: true },
          'leaves the ground (2)': { tick: 11, pos: [2.5012638199911734, 101.41999998688698, 1377.5], vel: [0.11763769845470062, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 16, pos: [3.2537029554611583, 102.25220334025373, 1377.5] },
          'lands (2)': { tick: 19, pos: [3.7694205397257523, 101.875, 1377.5], onGround: true },
          'top speed 5.166 b/s': { tick: 20, pos: [4.027724169577741, 101.875, 1377.5], vel: [0.14103379828063228, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [8.434594850021233, 101, 1377.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_fence', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1433.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1433.5], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [2.93263972405181, 101, 1433.5], vel: [0.11779307210407237, -0.0784000015258789, 0] },
          'touches a wall': { tick: 14, pos: [3.074999988079071, 101, 1433.5], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [3.074999988079071, 101, 1433.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_slab', {
    description: 'steps: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1329.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1329.5], onGround: true },
          'peak height 0.5': { tick: 12, pos: [2.7169015218135364, 101.5, 1329.5] },
          'leaves the ground (2)': { tick: 30, pos: [6.602098533030632, 101.42159999847412, 1329.5], vel: [0.11785906279261237, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 33, pos: [7.035511203223415, 101, 1329.5], onGround: true },
          'top speed 4.713 b/s': { tick: 34, pos: [7.271163140263165, 101, 1329.5], vel: [0.1286659725685947, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [8.845958294251853, 101, 1329.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_autojump_sneaking', {
    description: 'steps: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1381.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1381.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'lands (1)': { tick: 2, pos: [0.6573880118813518, 101, 1381.5], onGround: true },
          'touches a wall': { tick: 33, pos: [2.699999988079071, 101, 1381.5], isCollidedHorizontally: true },
          'final state': { tick: 63, pos: [2.699999988079071, 101, 1381.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
