// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stopped } = require('../../tools/java-harness')

describe('vanilla recordings: surface', () => {
  recorded('s_straddle_center', {
    description: 'straddle: forward+sprint 20 ticks, until still',
    steps: [press(['forward', 'sprint'], 20), stopped(3, 600)],
    groups: [
      {
        versions: ['1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0.02607428907331566, -0.0784000015258789, 0] },
          'top speed 4.857 b/s': { tick: 20, pos: [3.902689864670249, 101, 2747], vel: [0.21658550976534402, -0.0784000015258789, 0] },
          'final state': { tick: 61, pos: [5.8786083565455165, 101, 2747], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20', '1.20.4', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.026074288584128563, -0.0784000015258789, 0] },
          'top speed 4.857 b/s': { tick: 20, pos: [3.902689800831424, 101, 2747], vel: [0.21658550570192212, -0.0784000015258789, 0] },
          'final state': { tick: 61, pos: [5.878608255635928, 101, 2747], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('s_straddle_drift_to_ice', {
    description: 'straddle: forward+right 30 ticks, until still',
    steps: [press(['forward', 'right'], 30), stopped(3, 600)],
    groups: [
      {
        versions: ['1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0.038608028381237336, -0.0784000015258789, 0.038608028381237336] },
          'top speed 4.151 b/s': { tick: 30, pos: [4.358244743622319, 101, 2750.508244743623], vel: [0.13088647761575456, -0.0784000015258789, 0.13088647761575456] },
          'final state': { tick: 66, pos: [5.540279700714328, 101, 2751.690279700715], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20', '1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803531251473, -0.0784000015258789, 0.03860803531251473] },
          'top speed 4.151 b/s': { tick: 30, pos: [4.358245052390332, 101, 2750.5082450523905], vel: [0.13088648323862018, -0.0784000015258789, 0.13088648323862018] },
          'final state': { tick: 66, pos: [5.5402800602624085, 101, 2751.6902800602625], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'top speed 4.151 b/s': { tick: 30, pos: [4.358244661133539, 101, 2750.5082446611323], vel: [0.13088646996568784, -0.0784000015258789, 0.13088646996568784] },
          'final state': { tick: 69, pos: [5.548314939092623, 101, 2751.6983149390917], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('s_straddle_mostly_ice', {
    description: 'straddle: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3, 600)],
    groups: [
      {
        versions: ['1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0.020057144802124727, -0.0784000015258789, 0] },
          'top speed 4.023 b/s': { tick: 30, pos: [5.07781216193753, 101, 2747.1], vel: [0.17939983229683484, -0.0784000015258789, 0] },
          'final state': { tick: 69, pos: [6.708984645566104, 101, 2747.1], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20', '1.20.4', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.02005714406293894, -0.0784000015258789, 0] },
          'top speed 4.023 b/s': { tick: 30, pos: [5.077811993226893, 101, 2747.1], vel: [0.17939982568523546, -0.0784000015258789, 0] },
          'final state': { tick: 69, pos: [6.708984416740254, 101, 2747.1], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('s_straddle_mostly_stone', {
    description: 'straddle: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3, 600)],
    groups: [
      {
        versions: ['1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0.05350800074768003, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 30, pos: [6.716169705746736, 101, 2746.9], vel: [0.1178590474089648, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [6.972015769884708, 101, 2746.9], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20', '1.20.4', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 30, pos: [6.716170554523109, 101, 2746.9], vel: [0.11785906350182895, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [6.9720166535951495, 101, 2746.9], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
