// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, stopped, until } = require('../../tools/java-harness')

describe('vanilla recordings: world_border', () => {
  recorded('x_world_border_jump', {
    description: 'border: hold forward, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward'), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [29999982.598000005, 101.41999998688698, 0.5], vel: [0.053508008053839436, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [29999983.082542434, 102.25220334025373, 0.5] },
          'top speed 2.995 b/s': { tick: 10, pos: [29999983.63843048, 101.49520087700593, 0.5], vel: [0.13626929205361846, -0.3739040364667221, 0] },
          'touches a wall': { tick: 11, pos: [29999983.699999988, 101.1212968405392, 0.5], isCollidedHorizontally: true },
          'lands (1)': { tick: 12, pos: [29999983.699999988, 101, 0.5], onGround: true },
          'final state': { tick: 15, pos: [29999983.699999988, 101, 0.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_world_border_sprint_diagonal', {
    description: 'border: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.060238862958899186, -0.0784000015258789, -0.03478405917668391] },
          'leaves the ground (1)': { tick: 1, pos: [29999976.610327575, 101, 0.43629293931057866], vel: [0.060238862958899186, -0.0784000015258789, -0.03478405917668391], onGround: false },
          'lands (1)': { tick: 2, pos: [29999976.69263195, 101, 0.3887674696390455], onGround: true },
          'top speed 5.612 b/s': { tick: 31, pos: [29999983.61270323, 101, -3.607127490096105], vel: [0.13268473732680955, -0.0784000015258789, -0.0766168803379891] },
          'touches a wall': { tick: 32, pos: [29999983.699999988, 101, -3.7474514311235154], isCollidedHorizontally: true },
          'final state': { tick: 48, pos: [29999983.699999988, 101, -4.773428823973345], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('x_world_border_walk', {
    description: 'border: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [29999976.598000005, 101, 0.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [29999976.67110801, 101, 0.5], onGround: true },
          'top speed 4.317 b/s': { tick: 31, pos: [29999982.8179576, 101, 0.5], vel: [0.11785906381315, -0.0784000015258789, 0] },
          'touches a wall': { tick: 36, pos: [29999983.699999988, 101, 0.5], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [29999983.699999988, 101, 0.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
