// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stopped, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: sprint_sneak', () => {
  recorded('j_sprint_sneak_b', {
    description: 'flat: back+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['back', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 38.40199999663234], vel: [0, -0.0784000015258789, -0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 101, 38.40199999663234], vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 101, 38.342611988118655], onGround: true },
          'final state': { tick: 51, pos: [0.5, 101, 35.76655988151298], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_bl', {
    description: 'flat: back+left+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['back', 'left', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 1, pos: [0.5707106720016997, 101, 38.4292893279983], vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231], onGround: false },
          'top speed 2 b/s': { tick: 1, pos: [0.5707106720016997, 101, 38.4292893279983], vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'lands (1)': { tick: 2, pos: [0.6151987038589019, 101, 38.3848012961411], onGround: true },
          'final state': { tick: 51, pos: [3.161385213455404, 101, 35.8386147865446], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_br', {
    description: 'flat: back+right+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['back', 'right', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 1, pos: [0.42928932799830033, 101, 38.4292893279983], vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231], onGround: false },
          'top speed 2 b/s': { tick: 1, pos: [0.42928932799830033, 101, 38.4292893279983], vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'lands (1)': { tick: 2, pos: [0.3848012961410982, 101, 38.3848012961411], onGround: true },
          'final state': { tick: 51, pos: [-2.161385213455404, 101, 35.8386147865446], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_f', {
    description: 'flat: forward+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['forward', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 38.62740001240969], vel: [0, -0.0784000015258789, 0.0695604148553142], onGround: false },
          'top speed 2.548 b/s': { tick: 1, pos: [0.5, 101, 38.62740001240969], vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'lands (1)': { tick: 2, pos: [0.5, 101, 38.70460442764376], onGround: true },
          'final state': { tick: 51, pos: [0.5, 101, 42.05347237595006], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_fl', {
    description: 'flat: forward+left+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['forward', 'left', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.050190443980732705, -0.0784000015258789, 0.050190443980732705] },
          'leaves the ground (1)': { tick: 1, pos: [0.5919238793974007, 101, 38.5919238793974], vel: [0.050190443980732705, -0.0784000015258789, 0.050190443980732705], onGround: false },
          'top speed 2.6 b/s': { tick: 1, pos: [0.5919238793974007, 101, 38.5919238793974], vel: [0.050190443980732705, -0.0784000015258789, 0.050190443980732705] },
          'lands (1)': { tick: 2, pos: [0.649758323756891, 101, 38.64975832375689], onGround: true },
          'final state': { tick: 52, pos: [3.9620314364924467, 101, 41.96203143649243], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_fr', {
    description: 'flat: forward+right+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['forward', 'right', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.050190443980732705, -0.0784000015258789, 0.050190443980732705] },
          'leaves the ground (1)': { tick: 1, pos: [0.40807612060259935, 101, 38.5919238793974], vel: [-0.050190443980732705, -0.0784000015258789, 0.050190443980732705], onGround: false },
          'top speed 2.6 b/s': { tick: 1, pos: [0.40807612060259935, 101, 38.5919238793974], vel: [-0.050190443980732705, -0.0784000015258789, 0.050190443980732705] },
          'lands (1)': { tick: 2, pos: [0.350241676243109, 101, 38.64975832375689], onGround: true },
          'final state': { tick: 52, pos: [-2.9620314364924467, 101, 41.96203143649243], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_l', {
    description: 'flat: left+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['left', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 38.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 38.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'lands (1)': { tick: 2, pos: [0.6573880118813518, 101, 38.5], onGround: true },
          'final state': { tick: 51, pos: [3.233440118487015, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('j_sprint_sneak_r', {
    description: 'flat: right+sprint+sneak 40 ticks, until still, wait 3',
    steps: [press(['right', 'sprint', 'sneak'], 40), stopped(3), ticks(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.40199999663233754, 101, 38.5], vel: [-0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.40199999663233754, 101, 38.5], vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'lands (1)': { tick: 2, pos: [0.3426119881186483, 101, 38.5], onGround: true },
          'final state': { tick: 51, pos: [-2.233440118487015, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
