// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, stable, stopped, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: enchant', () => {
  recorded('q_depth_strider_1_jump_bottom', {
    description: 'water: hold forward, jump 1 ticks, wait 30, release all, until steady',
    steps: [hold('forward'), press('jump', 1), ticks(30), release(), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.032714578975383456, 0.02699999976158141, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5457333344181379, 98.03999999910593, 1833.5], vel: [0.032714578975383456, 0.02699999976158141, 0], onGround: false },
          'peak height 0.092': { tick: 4, pos: [0.7882682275334882, 98.09187999930144, 1833.5] },
          'top speed 2.696 b/s': { tick: 31, pos: [4.30335758254292, 97.54157774235696, 1833.5], vel: [0.10211708187768345, -0.024939555171213157, 0] },
          'final state': { tick: 36, pos: [4.61953395854158, 97.41678093125674, 1833.5], vel: [0.02549701952541462, -0.02498019443886232, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_depth_strider_1_sprint_swim', {
    description: 'water: forward+sprint 40 ticks, until steady',
    steps: [press(['forward', 'sprint'], 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.032714578975383456, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5457333344181379, 99, 1833.5], vel: [0.032714578975383456, -0.005, 0], onGround: false },
          'top speed 4.682 b/s': { tick: 27, pos: [5.656336593840802, 98.9884124798597, 1833.5], vel: [0.1968618309610017, 0, 0] },
          'touches a wall': { tick: 28, pos: [5.699999988079071, 98.9884124798597, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 45, pos: [5.699999988079071, 98.94745247937571, 1833.5], vel: [0, -0.016808000391483315, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_depth_strider_1_swim_surface', {
    description: 'water: forward 40 ticks, until steady',
    steps: [press('forward', 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.032714578975383456, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5457333344181379, 100.5, 1833.5], vel: [0.032714578975383456, -0.005, 0], onGround: false },
          'top speed 2.696 b/s': { tick: 40, pos: [5.516498990263125, 99.6249833399347, 1833.5], vel: [0.1021325179156365, -0.024996678417947976, 0] },
          'lands (1)': { tick: 45, pos: [5.832723159544262, 99.5, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [5.832723159544262, 99.5, 1833.5], vel: [0.02550087365984392, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_depth_strider_1_walk_bottom', {
    description: 'water: forward 40 ticks, until steady',
    steps: [press('forward', 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.032714578975383456, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5457333344181379, 98, 1833.5], vel: [0.032714578975383456, -0.005, 0], onGround: false },
          'top speed 2.696 b/s': { tick: 40, pos: [5.516498990263125, 97.1249833399347, 1833.5], vel: [0.1021325179156365, -0.024996678417947976, 0] },
          'lands (1)': { tick: 45, pos: [5.832723159544262, 97, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [5.832723159544262, 97, 1833.5], vel: [0.02550087365984392, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_depth_strider_2_jump_bottom', {
    description: 'water: hold forward, jump 1 ticks, wait 30, release all, until steady',
    steps: [hold('forward'), press('jump', 1), ticks(30), release(), stable(5)],
    groups: [
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.04532391496462014, 0.02699999976158141, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666652421156, 98.03999999910593, 1833.5], vel: [0.04532391496462014, 0.02699999976158141, 0], onGround: false },
          'peak height 0.092': { tick: 4, pos: [0.8988356065907843, 98.09187999930144, 1833.5] },
          'top speed 3.213 b/s': { tick: 31, pos: [5.1470584068758685, 97.54157774235696, 1833.5], vel: [0.11491940723502889, -0.024939555171213157, 0] },
          'final state': { tick: 36, pos: [5.475143110713602, 97.41678093125674, 1833.5], vel: [0.021524631233785126, -0.02498019443886232, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.045323919569476886, 0.02699999976158141, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666725436847, 98.03999999910593, 1833.5], vel: [0.045323919569476886, 0.02699999976158141, 0], onGround: false },
          'peak height 0.092': { tick: 4, pos: [0.8988356241475312, 98.09187999930144, 1833.5] },
          'top speed 3.213 b/s': { tick: 31, pos: [5.147058430353052, 97.54157774235696, 1833.5], vel: [0.11491940723522774, -0.024939555171213157, 0] },
          'final state': { tick: 36, pos: [5.475143134191352, 97.41678093125674, 1833.5], vel: [0.02152463123382237, -0.02498019443886232, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_depth_strider_2_sprint_swim', {
    description: 'water: forward+sprint 40 ticks, until steady',
    steps: [press(['forward', 'sprint'], 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.04532391496462014, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666652421156, 99, 1833.5], vel: [0.04532391496462014, -0.005, 0], onGround: false },
          'top speed 5.077 b/s': { tick: 23, pos: [5.47342124609144, 98.9884124798597, 1833.5], vel: [0.19851851910119978, 0, 0] },
          'touches a wall': { tick: 24, pos: [5.699999988079071, 98.9884124798597, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 45, pos: [5.699999988079071, 98.94745247937571, 1833.5], vel: [0, -0.016808000391483315, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.045323919569476886, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666725436847, 99, 1833.5], vel: [0.045323919569476886, -0.005, 0], onGround: false },
          'top speed 5.077 b/s': { tick: 23, pos: [5.473421274421732, 98.9884124798597, 1833.5], vel: [0.1985185191217949, 0, 0] },
          'touches a wall': { tick: 24, pos: [5.699999988079071, 98.9884124798597, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 45, pos: [5.699999988079071, 98.94745247937571, 1833.5], vel: [0, -0.016808000391483315, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_depth_strider_2_swim_surface', {
    description: 'water: forward 40 ticks, until steady',
    steps: [press('forward', 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.04532391496462014, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666652421156, 100.5, 1833.5], vel: [0.04532391496462014, -0.005, 0], onGround: false },
          'top speed 3.213 b/s': { tick: 40, pos: [6.592950088624745, 99.6249833399347, 1833.5], vel: [0.11492226492321755, -0.024996678417947976, 0] },
          'lands (1)': { tick: 45, pos: [6.921042950908519, 99.5, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [6.921042950908519, 99.5, 1833.5], vel: [0.02152516648440921, -0.005, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.045323919569476886, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666725436847, 100.5, 1833.5], vel: [0.045323919569476886, -0.005, 0], onGround: false },
          'top speed 3.213 b/s': { tick: 40, pos: [6.592950112102591, 99.6249833399347, 1833.5], vel: [0.11492226492322731, -0.024996678417947976, 0] },
          'lands (1)': { tick: 45, pos: [6.921042974386394, 99.5, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [6.921042974386394, 99.5, 1833.5], vel: [0.02152516648441104, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_depth_strider_2_walk_bottom', {
    description: 'water: forward 40 ticks, until steady',
    steps: [press('forward', 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.04532391496462014, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666652421156, 98, 1833.5], vel: [0.04532391496462014, -0.005, 0], onGround: false },
          'top speed 3.213 b/s': { tick: 34, pos: [5.629018954645292, 97.27493658166755, 1833.5], vel: [0.11492131233420276, -0.024987324976935933, 0] },
          'touches a wall': { tick: 35, pos: [5.699999988079071, 97.24994925669061, 1833.5], isCollidedHorizontally: true },
          'lands (1)': { tick: 45, pos: [6.286806586405637, 97, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [6.286806586405637, 97, 1833.5], vel: [0.01588906475860521, -0.005, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.045323919569476886, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5718666725436847, 98, 1833.5], vel: [0.045323919569476886, -0.005, 0], onGround: false },
          'top speed 3.213 b/s': { tick: 34, pos: [5.629018978122918, 97.27493658166755, 1833.5], vel: [0.11492131233427554, -0.024987324976935933, 0] },
          'touches a wall': { tick: 35, pos: [5.699999988079071, 97.24994925669061, 1833.5], isCollidedHorizontally: true },
          'lands (1)': { tick: 45, pos: [6.286806586405637, 97, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [6.286806586405637, 97, 1833.5], vel: [0.01588906475860521, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_depth_strider_3_jump_bottom', {
    description: 'water: hold forward, jump 1 ticks, wait 30, release all, until steady',
    steps: [hold('forward'), press('jump', 1), ticks(30), release(), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.05350800406718223, 0.02699999976158141, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5979999960660933, 98.03999999910593, 1833.5], vel: [0.05350800406718223, 0.02699999976158141, 0], onGround: false },
          'peak height 0.092': { tick: 4, pos: [0.9939312501695514, 98.09187999930144, 1833.5] },
          'top speed 3.596 b/s': { tick: 30, pos: [5.606233477330295, 97.56650218594957, 1833.5], vel: [0.12101583942829744, -0.024924443592613293, 0] },
          'touches a wall': { tick: 31, pos: [5.699999988079071, 97.54157774235696, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 36, pos: [5.699999988079071, 97.41678093125674, 1833.5], vel: [0, -0.02498019443886232, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_depth_strider_3_sprint_swim', {
    description: 'water: forward+sprint 40 ticks, until steady',
    steps: [press(['forward', 'sprint'], 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.05350800406718223, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5979999960660933, 99, 1833.5], vel: [0.05350800406718223, -0.005, 0], onGround: false },
          'top speed 5.303 b/s': { tick: 22, pos: [5.671348120038463, 98.9884124798597, 1833.5], vel: [0.1916906142983782, 0, 0] },
          'touches a wall': { tick: 23, pos: [5.699999988079071, 98.9884124798597, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 45, pos: [5.699999988079071, 98.94745247937571, 1833.5], vel: [0, -0.016808000391483315, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.05350800406718223, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5979999960660933, 99, 1833.5], vel: [0.05350800406718223, -0.005, 0], onGround: false },
          'top speed 5.303 b/s': { tick: 22, pos: [5.671349006773071, 98.9884124798597, 1833.5], vel: [0.19169067106804866, 0, 0] },
          'touches a wall': { tick: 23, pos: [5.699999988079071, 98.9884124798597, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 45, pos: [5.699999988079071, 98.94745247937571, 1833.5], vel: [0, -0.016808000391483315, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_depth_strider_3_swim_surface', {
    description: 'water: forward 40 ticks, until steady',
    steps: [press('forward', 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.05350800406718223, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5979999960660933, 100.5, 1833.5], vel: [0.05350800406718223, -0.005, 0], onGround: false },
          'top speed 3.596 b/s': { tick: 40, pos: [7.404396732932284, 99.6249833399347, 1833.5], vel: [0.12101652088476787, -0.024996678417947976, 0] },
          'lands (1)': { tick: 45, pos: [7.723383585116493, 99.5, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [7.723383585116493, 99.5, 1833.5], vel: [0.01670783223680942, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_depth_strider_3_walk_bottom', {
    description: 'water: forward 40 ticks, until steady',
    steps: [press('forward', 40), stable(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.05350800406718223, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5979999960660933, 98, 1833.5], vel: [0.05350800406718223, -0.005, 0], onGround: false },
          'top speed 3.596 b/s': { tick: 30, pos: [5.606233477330295, 97.37484522760518, 1833.5], vel: [0.12101583942829744, -0.024969052973454343, 0] },
          'touches a wall': { tick: 31, pos: [5.699999988079071, 97.34987617463172, 1833.5], isCollidedHorizontally: true },
          'lands (1)': { tick: 45, pos: [6.378653550295006, 97, 1833.5], onGround: true },
          'final state': { tick: 45, pos: [6.378653550295006, 97, 1833.5], vel: [0.013280310040867556, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_frost_walker_1', {
    description: 'water: forward 80 ticks, until still',
    steps: [press('forward', 80), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 27, pos: [-9.93140663326909, 101, 1833.5], vel: [0.11785905558757893, -0.0784000015258789, 0] },
          'final state': { tick: 120, pos: [2.1497986962290647, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_frost_walker_2', {
    description: 'water: forward 80 ticks, until still',
    steps: [press('forward', 80), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 27, pos: [-9.93140663326909, 101, 1833.5], vel: [0.11785905558757893, -0.0784000015258789, 0] },
          'final state': { tick: 120, pos: [2.1497986962290647, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_1_sprint_soul_sand', {
    description: 'surfaces: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.09773237517746804, -0.0784000015258789, 0] },
          'top speed 7.885 b/s': { tick: 30, pos: [11.853835339758824, 100.875, 1173.5], vel: [0.2152695761097252, -0.0784000015258789, 0] },
          'final state': { tick: 41, pos: [12.324252324878245, 100.875, 1173.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_1_sprint_soul_soil', {
    description: 'surfaces: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.09773237517746804, -0.0784000015258789, 0] },
          'top speed 7.885 b/s': { tick: 30, pos: [11.853835339758824, 101, 1177.5], vel: [0.2152695761097252, -0.0784000015258789, 0] },
          'final state': { tick: 41, pos: [12.324252324878245, 101, 1177.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_1_walk_soul_sand', {
    description: 'surfaces: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0751787550431689, -0.0784000015258789, 0] },
          'top speed 6.066 b/s': { tick: 30, pos: [9.233720062141606, 100.875, 1173.5], vel: [0.16559199243047706, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [9.593183849160809, 100.875, 1173.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_1_walk_soul_soil', {
    description: 'surfaces: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0751787550431689, -0.0784000015258789, 0] },
          'top speed 6.066 b/s': { tick: 30, pos: [9.233720062141606, 101, 1177.5], vel: [0.16559199243047706, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [9.593183849160809, 101, 1177.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_3_sprint_soul_sand', {
    description: 'surfaces: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.11234006126055314, -0.0784000015258789, 0] },
          'top speed 9.064 b/s': { tick: 30, pos: [13.55084988771255, 100.875, 1173.5], vel: [0.24744510019107016, -0.0784000015258789, 0] },
          'final state': { tick: 41, pos: [14.091578308876551, 100.875, 1173.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_3_sprint_soul_soil', {
    description: 'surfaces: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.11234006126055314, -0.0784000015258789, 0] },
          'top speed 9.064 b/s': { tick: 30, pos: [13.55084988771255, 101, 1177.5], vel: [0.24744510019107016, -0.0784000015258789, 0] },
          'final state': { tick: 41, pos: [14.091578308876551, 101, 1177.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_3_walk_soul_sand', {
    description: 'surfaces: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.08641543541887829, -0.0784000015258789, 0] },
          'top speed 6.972 b/s': { tick: 30, pos: [10.539115725754998, 100.875, 1173.5], vel: [0.1903423928680703, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [10.952307187288863, 100.875, 1173.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_soul_speed_3_walk_soul_soil', {
    description: 'surfaces: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.08641543541887829, -0.0784000015258789, 0] },
          'top speed 6.972 b/s': { tick: 30, pos: [10.539115725754998, 101, 1177.5], vel: [0.1903423928680703, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [10.952307187288863, 101, 1177.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_swift_sneak_1', {
    description: 'flat: forward+sneak 30 ticks, until still',
    steps: [press(['forward', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 101, 38.59800000336766], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'final state': { tick: 38, pos: [0.5, 101, 41.52715125297917], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_swift_sneak_1_edge', {
    description: 'ledges: forward+sneak 40 ticks, wait 5',
    steps: [press(['forward', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.08641543541887829, -0.0784000015258789, 0] },
          'top speed 3.165 b/s': { tick: 1, pos: [0.6582700098562242, 102, 1669.5], vel: [0.08641543541887829, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 42, pos: [2.3746887590481944, 101.92159999847412, 1669.5], vel: [0.0158110567631103, -0.1552320045166016, 0], onGround: false },
          'final state': { tick: 45, pos: [2.4179810147406124, 101.23152379758702, 1669.5], vel: [0.011914754886177301, -0.37663049823865513, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 102, 1669.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 42, pos: [2.379491405775724, 101.92159999847412, 1669.5], vel: [0.015811056751823396, -0.1552320045166016, 0], onGround: false },
          'final state': { tick: 45, pos: [2.422783661437237, 101.23152379758702, 1669.5], vel: [0.011914754877671817, -0.37663049823865513, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_swift_sneak_2', {
    description: 'flat: forward+sneak 30 ticks, until still',
    steps: [press(['forward', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 2.59 b/s': { tick: 30, pos: [0.5, 101, 42.316046250906176], vel: [0, -0.0784000015258789, 0.07071544434750895] },
          'final state': { tick: 39, pos: [0.5, 101, 42.467680351709774], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_swift_sneak_2_edge', {
    description: 'ledges: forward+sneak 40 ticks, wait 5',
    steps: [press(['forward', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 2.59 b/s': { tick: 14, pos: [2.2438135518808067, 102, 1669.5], vel: [0.07070884966188312, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 42, pos: [2.38264849041222, 101.92159999847412, 1669.5], vel: [0.02108141042679153, -0.1552320045166016, 0], onGround: false },
          'final state': { tick: 45, pos: [2.440371501860945, 101.23152379758702, 1669.5], vel: [0.015886340910252494, -0.37663049823865513, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_swift_sneak_3', {
    description: 'flat: forward+sneak 30 ticks, until still',
    steps: [press(['forward', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 3.238 b/s': { tick: 30, pos: [0.5, 101, 43.21609268228985], vel: [0, -0.0784000015258789, 0.08839429794622211] },
          'final state': { tick: 39, pos: [0.5, 101, 43.405635292237584], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_swift_sneak_3_edge', {
    description: 'ledges: forward+sneak 40 ticks, wait 5',
    steps: [press(['forward', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.20.4', '1.21.10', '1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 3.235 b/s': { tick: 11, pos: [2.1402818920320836, 102, 1669.5], vel: [0.08831215366816324, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 42, pos: [2.4362388335808047, 101.92159999847412, 1669.5], vel: [0.026351760896275344, -0.1552320045166016, 0], onGround: false },
          'final state': { tick: 45, pos: [2.508392592039805, 101.23152379758702, 1669.5], vel: [0.019857924527272933, -0.37663049823865513, 0], onGround: false }
        }
      }
    ]
  })
})
