// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, server, stopped, ticks, until } = require('../../tools/java-harness')

describe('vanilla recordings: food', () => {
  recorded('e_food_0_walk_jump', {
    description: 'flat: hold forward, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward'), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.8.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0.05350800074768003] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 38.59799998998642], vel: [0, 0.33319999363422365, 0.05350800074768003], onGround: false },
          'peak height 1.249': { tick: 5, pos: [0.5, 102.24918707874468, 38.9639718503234] },
          'lands (1)': { tick: 12, pos: [0.5, 101, 39.95574077898359], onGround: true },
          'top speed 3.229 b/s': { tick: 12, pos: [0.5, 101, 39.95574077898359], vel: [0, -0.0784000015258789, 0.1469113679031433] },
          'final state': { tick: 21, pos: [0.5, 101, 40.270760692601726], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0.05350800074768003] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 38.59799998998642], vel: [0, 0.33319999363422365, 0.05350800074768003], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 39.08254239440103] },
          'lands (1)': { tick: 12, pos: [0.5, 101, 39.95574077898359], onGround: true },
          'top speed 3.229 b/s': { tick: 12, pos: [0.5, 101, 39.95574077898359], vel: [0, -0.0784000015258789, 0.1469113679031433] },
          'final state': { tick: 22, pos: [0.5, 101, 40.274653039700596], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 38.59800000336766], vel: [0, 0.33319999363422365, 0.053508008053839436], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 39.0825424344534] },
          'lands (1)': { tick: 12, pos: [0.5, 101, 39.95574083041286], onGround: true },
          'top speed 3.229 b/s': { tick: 12, pos: [0.5, 101, 39.95574083041286], vel: [0, -0.0784000015258789, 0.14691136860507253] },
          'final state': { tick: 22, pos: [0.5, 101, 40.27465309265359], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('e_food_6_sprint', {
    description: 'flat: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.8.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.58102023939666], vel: [0, -0.0784000015258789, 0.15321675446334057] },
          'final state': { tick: 39, pos: [0.5, 101, 46.90956070188635], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.9.4', '1.10.2', '1.11.2', '1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.58102023939666], vel: [0, -0.0784000015258789, 0.15321675446334057] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362010721519], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956040585360501] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.58102118458192], vel: [0, -0.0784000015258789, 0.15321677238412473] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362109130253], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.5810222303349], vel: [0, -0.0784000015258789, 0.15321679221168047] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362218009678], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('e_food_7_sprint', {
    description: 'flat: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.8.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.58102023939666], vel: [0, -0.0784000015258789, 0.15321675446334057] },
          'final state': { tick: 39, pos: [0.5, 101, 46.90956070188635], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.9.4', '1.10.2', '1.11.2', '1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.58102023939666], vel: [0, -0.0784000015258789, 0.15321675446334057] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362010721519], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956040585360501] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.58102118458192], vel: [0, -0.0784000015258789, 0.15321677238412473] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362109130253], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.5810222303349], vel: [0, -0.0784000015258789, 0.15321679221168047] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362218009678], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('e_food_drop_mid_sprint', {
    description: 'flat: hold forward+sprint, wait 15, server food, wait 25, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(15), server({ food: 6 }), ticks(25), release(), stopped(3)],
    groups: [
      {
        versions: ['1.8.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.063399869564975], vel: [0, -0.0784000015258789, 0.15321641483931187] },
          'final state': { tick: 49, pos: [0.5, 101, 49.3919396038038], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.9.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 48.99864282859956], vel: [0, -0.0784000015258789, 0.15321611629529777] },
          'final state': { tick: 50, pos: [0.5, 101, 49.33124131109565], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.10.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 48.99864218843598], vel: [0, -0.0784000015258789, 0.1532164069295296] },
          'final state': { tick: 50, pos: [0.5, 101, 49.33124130183507], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.11.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.322429928727004], vel: [0, -0.0784000015258789, 0.15321674854911124] },
          'final state': { tick: 50, pos: [0.5, 101, 49.65502978370704], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.38718760985601], vel: [0, -0.0784000015258789, 0.15321675645889346] },
          'final state': { tick: 50, pos: [0.5, 101, 49.71978748200645], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956040585360501] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.38718888326073], vel: [0, -0.0784000015258789, 0.15321677437967782] },
          'final state': { tick: 50, pos: [0.5, 101, 49.719788794313246], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.25767486506046], vel: [0, -0.0784000015258789, 0.15321677181065893] },
          'final state': { tick: 50, pos: [0.5, 101, 49.590274770536205], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.38719029215573], vel: [0, -0.0784000015258789, 0.15321679420723386] },
          'final state': { tick: 50, pos: [0.5, 101, 49.71979024624951], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.2576749060798], vel: [0, -0.0784000015258789, 0.15321675318787065] },
          'final state': { tick: 50, pos: [0.5, 101, 49.590274771129565], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.19291718528877], vel: [0, -0.0784000015258789, 0.1532167452780836] },
          'final state': { tick: 50, pos: [0.5, 101, 49.525517033168136], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.38719029215573], vel: [0, -0.0784000015258789, 0.15321679420723386] },
          'final state': { tick: 50, pos: [0.5, 101, 49.71979024624951], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.5', '1.21.6'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.2576749060798], vel: [0, -0.0784000015258789, 0.15321675318787065] },
          'final state': { tick: 50, pos: [0.5, 101, 49.590274771129565], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.7'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.128159732726175], vel: [0, -0.0784000015258789, 0.15321661559259347] },
          'final state': { tick: 50, pos: [0.5, 101, 49.46075929908686], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.8'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 48.86913320667827], vel: [0, -0.0784000015258789, 0.15321460582295549] },
          'final state': { tick: 50, pos: [0.5, 101, 49.20172841027121], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 48.998645272927895], vel: [0, -0.0784000015258789, 0.1532161540432461] },
          'final state': { tick: 50, pos: [0.5, 101, 49.331243837366486], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.38719029215573], vel: [0, -0.0784000015258789, 0.15321679420723386] },
          'final state': { tick: 50, pos: [0.5, 101, 49.71979024624951], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 48.86913320667827], vel: [0, -0.0784000015258789, 0.15321460582295549] },
          'final state': { tick: 50, pos: [0.5, 101, 49.20172841027121], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.1'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.128159732726175], vel: [0, -0.0784000015258789, 0.15321661559259347] },
          'final state': { tick: 50, pos: [0.5, 101, 49.46075929908686], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 48.86913320667827], vel: [0, -0.0784000015258789, 0.15321460582295549] },
          'final state': { tick: 50, pos: [0.5, 101, 49.20172841027121], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
