// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, server, stopped, ticks, until } = require('../../tools/java-harness')

describe('vanilla recordings: food', () => {
  recorded('e_food_0_walk_jump', {
    description: 'flat: hold forward, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward'), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 38.59800000336766], vel: [0, 0.33319999363422365, 0.053508008053839436], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 39.0825424344534] },
          'lands (1)': { tick: 12, pos: [0.5, 101, 39.95574083041286], onGround: true },
          'top speed 3.229 b/s': { tick: 12, pos: [0.5, 101, 39.95574083041286], vel: [0, -0.0784000015258789, 0.14691136860507253] },
          'final state': { tick: 22, pos: [0.5, 101, 40.27465309265359], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('e_food_6_sprint', {
    description: 'flat: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.5810222303349], vel: [0, -0.0784000015258789, 0.15321679221168047] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362218009678], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('e_food_7_sprint', {
    description: 'flat: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 30, pos: [0.5, 101, 46.5810222303349], vel: [0, -0.0784000015258789, 0.15321679221168047] },
          'final state': { tick: 40, pos: [0.5, 101, 46.91362218009678], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('e_food_drop_mid_sprint', {
    description: 'flat: hold forward+sprint, wait 15, server food, wait 25, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(15), server({ food: 6 }), ticks(25), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.612 b/s': { tick: 40, pos: [0.5, 101, 49.38719029215573], vel: [0, -0.0784000015258789, 0.15321679420723386] },
          'final state': { tick: 50, pos: [0.5, 101, 49.71979024624951], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
