// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (1ba1386) from test/fixtures/java/*.pfix. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: honey', () => {
  recorded('b_honey_fall_near_not_touching', {
    description: 'honeyWall: wait 60, until steady',
    steps: [ticks(60), stable(5)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 118, 1987.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 23, pos: [0.5, 101, 1987.5], onGround: true },
          'final state': { tick: 65, pos: [0.5, 101, 1987.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_honey_jump_against', {
    description: 'honeyWall: hold forward, jump 1 ticks, wait 30, release all, until steady',
    steps: [hold('forward'), press('jump', 1), ticks(30), release(), stable(5)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [1.5980000033676625, 101.41999998688698, 1987.5], vel: [0.053508008053839436, 0.33319999363422365, 0], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [1.5980000033676625, 101.41999998688698, 1987.5], vel: [0.053508008053839436, 0.33319999363422365, 0] },
          'touches a wall': { tick: 4, pos: [1.762499988079071, 102.16610926093821, 1987.5], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 6, pos: [1.762499988079071, 102.25220334025373, 1987.5] },
          'lands (1)': { tick: 17, pos: [1.762499988079071, 101, 1987.5], onGround: true },
          'final state': { tick: 36, pos: [1.762499988079071, 101, 1987.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_honey_slide_pressed', {
    description: 'honeyWall: hold forward, wait 100, release all, until steady',
    steps: [hold('forward'), ticks(100), release(), stable(5)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [1.5980000033676625, 118, 1987.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [1.5980000033676625, 118, 1987.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'touches a wall': { tick: 4, pos: [1.762499988079071, 117.63896799147797, 1987.5], isCollidedHorizontally: true },
          'final state': { tick: 105, pos: [1.762499988079071, 104.77156774104373, 1987.5], vel: [0, -0.12740000247955321, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [1.5980000033676625, 118, 1987.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [1.5980000033676625, 118, 1987.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'touches a wall': { tick: 4, pos: [1.762499988079071, 117.63896799147797, 1987.5], isCollidedHorizontally: true },
          'final state': { tick: 105, pos: [1.762499988079071, 104.77156774104373, 1987.5], vel: [0, -0.12740000247955321, 0], onGround: false }
        }
      }
    ]
  })

  recorded('b_honey_slide_sneak', {
    description: 'honeyWall: hold forward+sneak, wait 100, release all, until steady',
    steps: [hold('forward', 'sneak'), ticks(100), release(), stable(5)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [1.5, 118, 1987.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'top speed 1.217 b/s': { tick: 5, pos: [1.7405742265228723, 117.23152379758702, 1987.5], vel: [0.009098467586912531, -0.12740000247955321, 0] },
          'touches a wall': { tick: 7, pos: [1.7624999880790713, 116.97672379262792, 1987.5], isCollidedHorizontally: true },
          'final state': { tick: 105, pos: [1.7624999880790713, 104.49152354963232, 1987.5], vel: [0, -0.12740000247955321, 0], onGround: false }
        }
      }
    ]
  })

  recorded('b_honey_slide_touching', {
    description: 'honeyWall: wait 100, until steady',
    steps: [ticks(100), stable(5)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [1.7, 118, 1987.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 23, pos: [1.7, 101, 1987.5], onGround: true },
          'final state': { tick: 105, pos: [1.7, 101, 1987.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
