// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stopped } = require('../../tools/java-harness')

describe('vanilla recordings: step', () => {
  recorded('g_step_attr_0_4_slab', {
    description: 'steps: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1329.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1329.5], onGround: true },
          'top speed 4.309 b/s': { tick: 11, pos: [2.5012638199911734, 101, 1329.5], vel: [0.11763769845470062, -0.0784000015258789, 0] },
          'touches a wall': { tick: 12, pos: [2.699999988079071, 101, 1329.5], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [2.699999988079071, 101, 1329.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_step_attr_0_carpet', {
    description: 'steps: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1341.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1341.5], onGround: true },
          'top speed 4.309 b/s': { tick: 11, pos: [2.5012638199911734, 101, 1341.5], vel: [0.11763769845470062, -0.0784000015258789, 0] },
          'touches a wall': { tick: 12, pos: [2.699999988079071, 101, 1341.5], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [2.699999988079071, 101, 1341.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_step_attr_1_full_block', {
    description: 'steps: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1381.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1381.5], onGround: true },
          'peak height 1': { tick: 12, pos: [2.7169015218135364, 102, 1381.5] },
          'leaves the ground (2)': { tick: 30, pos: [6.602098533030632, 101.92159999847412, 1381.5], vel: [0.11785906279261237, -0.1552320045166016, 0], onGround: false },
          'top speed 4.317 b/s': { tick: 30, pos: [6.602098533030632, 101.92159999847412, 1381.5], vel: [0.11785906279261237, -0.1552320045166016, 0] },
          'lands (2)': { tick: 34, pos: [7.013623621066245, 101, 1381.5], onGround: true },
          'final state': { tick: 43, pos: [7.186928667174831, 101, 1381.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_step_attr_2_5_chest', {
    description: 'steps: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5980000033676625, 101, 1377.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.6711080113648775, 101, 1377.5], onGround: true },
          'peak height 0.875': { tick: 13, pos: [2.93263972405181, 101.875, 1377.5] },
          'leaves the ground (2)': { tick: 30, pos: [6.602098533030632, 101.79659999847412, 1377.5], vel: [0.11785906279261237, -0.1552320045166016, 0], onGround: false },
          'top speed 4.317 b/s': { tick: 30, pos: [6.602098533030632, 101.79659999847412, 1377.5], vel: [0.11785906279261237, -0.1552320045166016, 0] },
          'lands (2)': { tick: 34, pos: [7.013623621066245, 101, 1377.5], onGround: true },
          'final state': { tick: 43, pos: [7.186928667174831, 101, 1377.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
