// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, look, press, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: water', () => {
  recorded('b_flow_drift_around_bend', {
    description: 'flow: wait 250',
    steps: [ticks(250)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.011200000166893006, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-3.486, 101, 1887.5], vel: [0.011200000166893006, -0.005, 0], onGround: false },
          'enters water': { tick: 1, pos: [-3.486, 101, 1887.5], isInWater: true },
          'lands (1)': { tick: 2, pos: [-3.460799999833107, 101, 1887.5], onGround: true },
          'top speed 1.4 b/s': { tick: 50, pos: [-0.2799958326376065, 101, 1887.5], vel: [0.05599920491296243, -0.005, 0] },
          'touches a wall': { tick: 68, pos: [0.699999988079071, 101, 1887.9951209216142], isCollidedHorizontally: true },
          'final state': { tick: 250, pos: [0.699999988079071, 101, 1890.699999988079], vel: [0, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_flow_idle_drift', {
    description: 'flow: wait 200',
    steps: [ticks(200)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-3.5, 101, 1881.5], vel: [0, -0.005, 0], onGround: false },
          'enters water': { tick: 1, pos: [-3.5, 101, 1881.5], isInWater: true },
          'lands (1)': { tick: 2, pos: [-3.5, 101, 1881.5], onGround: true },
          'final state': { tick: 200, pos: [-3.5, 101, 1881.5], vel: [0, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_flow_sprint_with_flow', {
    description: 'flow: forward+sprint 30 ticks, until steady',
    steps: [press(['forward', 'sprint'], 30), stable(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.01568000018835067, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-3.4804000000566244, 101, 1881.5], vel: [0.01568000018835067, -0.005, 0], onGround: false },
          'enters water': { tick: 1, pos: [-3.4804000000566244, 101, 1881.5], isInWater: true },
          'lands (1)': { tick: 2, pos: [-3.445119999924898, 101, 1881.5], onGround: true },
          'top speed 3.345 b/s': { tick: 30, pos: [0.311031961110353, 101, 1881.5], vel: [0.1337936515102384, -0.005, 0] },
          'final state': { tick: 35, pos: [0.9225431129540912, 101, 1881.5], vel: [0.08149142843127175, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_flow_walk_across', {
    description: 'flow: forward 20 ticks, until steady',
    steps: [press('forward', 20), stable(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [3.5, 101, 1879.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [3.5, 101, 1879.6711080113648], onGround: true },
          'enters water': { tick: 3, pos: [3.5, 101, 1879.8356363039272], isInWater: true },
          'top speed 3.291 b/s': { tick: 3, pos: [3.5, 101, 1879.8356363039272], vel: [0.007644000887870789, -0.0784000015258789, 0.08983245817338027] },
          'final state': { tick: 25, pos: [4.8000040832828885, 101, 1881.8219263464127], vel: [0.05564319972854948, -0.005, 0.0257744723921543], onGround: true }
        }
      }
    ]
  })

  recorded('b_flow_walk_against', {
    description: 'flow: forward 60 ticks, until steady',
    steps: [press('forward', 60), stable(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.01208000013470649, -0.005, 1.9202462879198486e-18] },
          'leaves the ground (1)': { tick: 1, pos: [9.484900000056625, 101, 1881.5], vel: [-0.01208000013470649, -0.005, 1.9202462879198486e-18], onGround: false },
          'enters water': { tick: 1, pos: [9.484900000056625, 101, 1881.5], isInWater: true },
          'lands (1)': { tick: 2, pos: [9.456317099221707, 101, 1881.5], onGround: true },
          'top speed 1.626 b/s': { tick: 19, pos: [8.264439173555031, 101, 1881.5], vel: [-0.0650400619872233, -0.005, 9.462863636986973e-18] },
          'final state': { tick: 65, pos: [5.7766968357658754, 101, 1881.5], vel: [0.029878637269210813, -0.005, 3.146127118619548e-18], onGround: true }
        }
      }
    ]
  })

  recorded('b_flow_walk_around_bend', {
    description: 'flow: forward 18 ticks, look 0/0, forward 25 ticks, until steady',
    steps: [press('forward', 18), look(0, 0), press('forward', 25), stable(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.026880000355243676, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-3.4664000000566246, 101, 1887.5], vel: [0.026880000355243676, -0.005, 0], onGround: false },
          'enters water': { tick: 1, pos: [-3.4664000000566246, 101, 1887.5], isInWater: true },
          'lands (1)': { tick: 2, pos: [-3.405919999758005, 101, 1887.5], onGround: true },
          'top speed 3.299 b/s': { tick: 18, pos: [-1.13589423319302, 101, 1887.5], vel: [0.13197887380170126, -0.005, 0] },
          'touches a wall': { tick: 23, pos: [-0.5304836382363911, 101, 1887.699999988079], isCollidedHorizontally: true },
          'final state': { tick: 48, pos: [0.699999988079071, 101, 1889.0571564786183], vel: [0, -0.005, 0.045735607834015944], onGround: true }
        }
      }
    ]
  })
})
