// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, stable, stopped, ticks, until } = require('../../tools/java-harness')

describe('vanilla recordings: ceiling', () => {
  recorded('g_ceiling_jump_under_gap1', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101.39999997615814, 1493.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.4': { tick: 1, pos: [8.5, 101.39999997615814, 1493.5] },
          'lands (1)': { tick: 4, pos: [8.5, 101, 1493.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101, 1493.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_jump_under_gap1_5', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101, 1489.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [8.5, 101, 1489.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101, 1489.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_jump_under_gap1_75', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101.20000004768372, 1485.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [8.5, 101.20000004768372, 1485.5] },
          'lands (1)': { tick: 3, pos: [8.5, 101, 1485.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101, 1485.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_jump_under_gap1_875', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101.20000004768372, 1481.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [8.5, 101.20000004768372, 1481.5] },
          'lands (1)': { tick: 2, pos: [8.5, 101.125, 1481.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101.125, 1481.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_jump_under_gap1_9375', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101.20000004768372, 1477.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [8.5, 101.20000004768372, 1477.5] },
          'lands (1)': { tick: 3, pos: [8.5, 101.0625, 1477.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101.0625, 1477.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_jump_under_gap2', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101.20000004768372, 1473.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [8.5, 101.20000004768372, 1473.5] },
          'lands (1)': { tick: 3, pos: [8.5, 101, 1473.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101, 1473.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_jump_under_gap2_5', {
    description: 'ceilings: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(5), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.5, 101.41999998688698, 1497.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 0.7': { tick: 2, pos: [8.5, 101.70000004768372, 1497.5] },
          'lands (1)': { tick: 6, pos: [8.5, 101, 1497.5], onGround: true },
          'final state': { tick: 11, pos: [8.5, 101, 1497.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap1', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1493.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'touches a wall': { tick: 49, pos: [3.699999988079071, 101, 1493.5], isCollidedHorizontally: true },
          'final state': { tick: 63, pos: [3.699999988079071, 101, 1493.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap1_5', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1489.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'final state': { tick: 68, pos: [4.532785757997848, 101, 1489.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap1_75', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1485.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.25': { tick: 49, pos: [3.746349448909228, 101.25, 1485.5] },
          'final state': { tick: 68, pos: [4.532785757997848, 101.25, 1485.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap1_875', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1481.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.125': { tick: 49, pos: [3.746349448909228, 101.125, 1481.5] },
          'final state': { tick: 68, pos: [4.532785757997848, 101.125, 1481.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap1_9375', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1477.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.063': { tick: 49, pos: [3.746349448909228, 101.0625, 1477.5] },
          'final state': { tick: 68, pos: [4.532785757997848, 101.0625, 1477.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap2', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1473.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'final state': { tick: 68, pos: [4.532785757997848, 101, 1473.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sneak_gap2_5', {
    description: 'ceilings: forward+sneak 60 ticks, until still',
    steps: [press(['forward', 'sneak'], 60), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 101, 1497.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'final state': { tick: 68, pos: [4.532785757997848, 101, 1497.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap1', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'top speed 5.608 b/s': { tick: 12, pos: [3.5301566055593403, 101, 1493.5], vel: [0.15310924216284458, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [3.699999988079071, 101.41999998688698, 1493.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'touches a wall': { tick: 13, pos: [3.699999988079071, 101.41999998688698, 1493.5], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 18, pos: [3.699999988079071, 102.25220334025373, 1493.5] },
          'lands (1)': { tick: 24, pos: [3.699999988079071, 101, 1493.5], onGround: true },
          'final state': { tick: 27, pos: [3.699999988079071, 101, 1493.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap1_5', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'top speed 5.608 b/s': { tick: 12, pos: [3.5301566055593403, 101, 1489.5], vel: [0.15310924216284458, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [3.699999988079071, 101.41999998688698, 1489.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'touches a wall': { tick: 13, pos: [3.699999988079071, 101.41999998688698, 1489.5], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 18, pos: [3.699999988079071, 102.25220334025373, 1489.5] },
          'lands (1)': { tick: 24, pos: [3.699999988079071, 101, 1489.5], onGround: true },
          'final state': { tick: 27, pos: [3.699999988079071, 101, 1489.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap1_75', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'top speed 5.608 b/s': { tick: 12, pos: [3.5301566055593403, 101, 1485.5], vel: [0.15310924216284458, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [3.699999988079071, 101.41999998688698, 1485.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'touches a wall': { tick: 13, pos: [3.699999988079071, 101.41999998688698, 1485.5], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 18, pos: [3.699999988079071, 102.25220334025373, 1485.5] },
          'lands (1)': { tick: 24, pos: [3.699999988079071, 101, 1485.5], onGround: true },
          'final state': { tick: 27, pos: [3.699999988079071, 101, 1485.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap1_875', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [4.010665860131872, 101.125, 1481.5], vel: [0.26235808347018313, -0.0784000015258789, 0], onGround: false },
          'peak height 0.125': { tick: 13, pos: [4.010665860131872, 101.125, 1481.5] },
          'top speed 9.61 b/s': { tick: 13, pos: [4.010665860131872, 101.125, 1481.5], vel: [0.26235808347018313, -0.0784000015258789, 0] },
          'lands (1)': { tick: 14, pos: [4.298503942798287, 101.125, 1481.5], onGround: true },
          'final state': { tick: 25, pos: [4.87089125248597, 101.125, 1481.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap1_9375', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [4.010665860131872, 101.0625, 1477.5], vel: [0.26235808347018313, -0.0784000015258789, 0], onGround: false },
          'peak height 0.063': { tick: 13, pos: [4.010665860131872, 101.0625, 1477.5] },
          'top speed 9.61 b/s': { tick: 13, pos: [4.010665860131872, 101.0625, 1477.5], vel: [0.26235808347018313, -0.0784000015258789, 0] },
          'lands (1)': { tick: 14, pos: [4.298503942798287, 101.0625, 1477.5], onGround: true },
          'final state': { tick: 25, pos: [4.87089125248597, 101.0625, 1477.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap2', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [4.010665860131872, 101, 1473.5], vel: [0.26235808347018313, -0.0784000015258789, 0], onGround: false },
          'top speed 9.61 b/s': { tick: 13, pos: [4.010665860131872, 101, 1473.5], vel: [0.26235808347018313, -0.0784000015258789, 0] },
          'lands (1)': { tick: 14, pos: [4.298503942798287, 101, 1473.5], onGround: true },
          'final state': { tick: 25, pos: [4.87089125248597, 101, 1473.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_sprint_jump_gap2_5', {
    description: 'ceilings: hold forward+sprint, wait 12, jump 1 ticks, until onGround, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(12), press('jump', 1), until('onGround', 40), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 13, pos: [4.010665860131872, 101.41999998688698, 1497.5], vel: [0.26235808347018313, 0.33319999363422365, 0], onGround: false },
          'top speed 9.61 b/s': { tick: 13, pos: [4.010665860131872, 101.41999998688698, 1497.5], vel: [0.26235808347018313, 0.33319999363422365, 0] },
          'peak height 0.7': { tick: 14, pos: [4.298503942798287, 101.70000004768372, 1497.5] },
          'lands (1)': { tick: 18, pos: [5.445968025632172, 101, 1497.5], onGround: true },
          'final state': { tick: 29, pos: [6.015401449600205, 101, 1497.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap1', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 16, pos: [3.694159788768005, 101, 1493.5], vel: [0.11785171235343735, -0.0784000015258789, 0] },
          'touches a wall': { tick: 17, pos: [3.699999988079071, 101, 1493.5], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [3.699999988079071, 101, 1493.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap1_5', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 16, pos: [3.694159788768005, 101, 1489.5], vel: [0.11785171235343735, -0.0784000015258789, 0] },
          'touches a wall': { tick: 17, pos: [3.699999988079071, 101, 1489.5], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [3.699999988079071, 101, 1489.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap1_75', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 16, pos: [3.694159788768005, 101, 1485.5], vel: [0.11785171235343735, -0.0784000015258789, 0] },
          'touches a wall': { tick: 17, pos: [3.699999988079071, 101, 1485.5], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [3.699999988079071, 101, 1485.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap1_875', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.125': { tick: 17, pos: [3.910011504489105, 101.125, 1481.5] },
          'top speed 4.317 b/s': { tick: 40, pos: [8.874761235223515, 101.125, 1481.5], vel: [0.11785906503686992, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [9.13060733762779, 101.125, 1481.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap1_9375', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.063': { tick: 17, pos: [3.910011504489105, 101.0625, 1477.5] },
          'top speed 4.317 b/s': { tick: 40, pos: [8.874761235223515, 101.0625, 1477.5], vel: [0.11785906503686992, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [9.13060733762779, 101.0625, 1477.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap2', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 40, pos: [8.874761235223515, 101, 1473.5], vel: [0.11785906503686992, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [9.13060733762779, 101, 1473.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_ceiling_walk_gap2_5', {
    description: 'ceilings: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 4.317 b/s': { tick: 40, pos: [8.874761235223515, 101, 1497.5], vel: [0.11785906503686992, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [9.13060733762779, 101, 1497.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
