// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, stable, stopped, ticks, until } = require('../../tools/java-harness')

describe('vanilla recordings: collision', () => {
  recorded('g_wall_chunk_border_x', {
    description: 'walls: forward 20 ticks, until still',
    steps: [press('forward', 20), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [13.598000003367662, 101, 1717.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [13.671108011364877, 101, 1717.5], onGround: true },
          'top speed 4.309 b/s': { tick: 11, pos: [15.501263819991172, 101, 1717.5], vel: [0.11763769845470062, -0.0784000015258789, 0] },
          'touches a wall': { tick: 12, pos: [15.699999988079071, 101, 1717.5], isCollidedHorizontally: true },
          'final state': { tick: 23, pos: [15.699999988079071, 101, 1717.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_cobblestone_wall', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 1720.6711080113648], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 1722.9326397240516], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'touches a wall': { tick: 14, pos: [0.5, 101, 1722.949999988079], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [0.5, 101, 1722.949999988079], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_door_closed', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [6.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [6.5, 101, 1720.6711080113648], onGround: true },
          'top speed 4.317 b/s': { tick: 30, pos: [6.5, 101, 1726.6020985330301], vel: [0, -0.0784000015258789, 0.11785906279261237] },
          'final state': { tick: 40, pos: [6.5, 101, 1726.8579446305625], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_fence', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [3.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [3.5, 101, 1720.6711080113648], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [3.5, 101, 1722.9326397240516], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'touches a wall': { tick: 14, pos: [3.5, 101, 1723.074999988079], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [3.5, 101, 1723.074999988079], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_glass_pane', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [-6.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [-6.5, 101, 1720.6711080113648], onGround: true },
          'top speed 4.317 b/s': { tick: 30, pos: [-6.5, 101, 1726.6020985330301], vel: [0, -0.0784000015258789, 0.11785906279261237] },
          'final state': { tick: 40, pos: [-6.5, 101, 1726.8579446305625], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_glass_pane_edge', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [-5.9, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [-5.9, 101, 1720.6711080113648], onGround: true },
          'top speed 4.317 b/s': { tick: 30, pos: [-5.9, 101, 1726.6020985330301], vel: [0, -0.0784000015258789, 0.11785906279261237] },
          'final state': { tick: 40, pos: [-5.9, 101, 1726.8579446305625], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_head_on', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [11.598000003367662, 101, 1717.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [11.671108011364877, 101, 1717.5], onGround: true },
          'top speed 4.317 b/s': { tick: 21, pos: [15.659368060515174, 101, 1717.5], vel: [0.117858543798978, -0.0784000015258789, 0] },
          'touches a wall': { tick: 22, pos: [15.699999988079071, 101, 1717.5], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [15.699999988079071, 101, 1717.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_inner_corner', {
    description: 'walls: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'leaves the ground (1)': { tick: 1, pos: [8.43070353424838, 101, 1708.5692964657517], vel: [-0.03783587469512084, -0.0784000015258789, 0.03783587469512084], onGround: false },
          'lands (1)': { tick: 2, pos: [8.379008366919233, 101, 1708.6209916330808], onGround: true },
          'top speed 4.317 b/s': { tick: 16, pos: [6.322043812989956, 101, 1710.6779561870098], vel: [-0.08333134711541076, -0.0784000015258789, 0.08333134711541076] },
          'touches a wall': { tick: 17, pos: [6.300000011920929, 101, 1710.699999988079], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [6.300000011920929, 101, 1710.699999988079], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_inner_corner_sprint', {
    description: 'walls: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.04918664020454862, -0.0784000015258789, 0.04918664020454862] },
          'leaves the ground (1)': { tick: 1, pos: [8.409914588843606, 101, 1708.5900854111565], vel: [-0.04918664020454862, -0.0784000015258789, 0.04918664020454862], onGround: false },
          'lands (1)': { tick: 2, pos: [8.342710868731123, 101, 1708.657289131269], onGround: true },
          'top speed 5.607 b/s': { tick: 12, pos: [6.462137982272516, 101, 1710.5378620177278], vel: [-0.10822952744127408, -0.0784000015258789, 0.10822952744127408] },
          'touches a wall': { tick: 13, pos: [6.300000011920929, 101, 1710.699999988079], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [6.300000011920929, 101, 1710.699999988079], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_iron_bars', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [-3.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [-3.5, 101, 1720.6711080113648], onGround: true },
          'top speed 4.317 b/s': { tick: 30, pos: [-3.5, 101, 1726.6020985330301], vel: [0, -0.0784000015258789, 0.11785906279261237] },
          'final state': { tick: 40, pos: [-3.5, 101, 1726.8579446305625], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_jump_over_fence', {
    description: 'walls: hold forward+sprint, wait 5, jump 1 ticks, until onGround, wait 5, release all, until still',
    steps: [hold('forward', 'sprint'), ticks(5), press('jump', 1), until('onGround', 40), ticks(5), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'leaves the ground (1)': { tick: 1, pos: [3.5, 101, 1720.6274000124097], vel: [0, -0.0784000015258789, 0.0695604148553142], onGround: false },
          'lands (1)': { tick: 2, pos: [3.5, 101, 1720.7224404264612], onGround: true },
          'leaves the ground (2)': { tick: 6, pos: [3.5, 101.41999998688698, 1721.9109880184105], vel: [0, 0.33319999363422365, 0.25648629755013824], onGround: false },
          'top speed 9.395 b/s': { tick: 6, pos: [3.5, 101.41999998688698, 1721.9109880184105], vel: [0, 0.33319999363422365, 0.25648629755013824] },
          'touches a wall': { tick: 11, pos: [3.5, 102.25220334025373, 1723.074999988079], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 11, pos: [3.5, 102.25220334025373, 1723.074999988079] },
          'lands (2)': { tick: 17, pos: [3.5, 101, 1723.074999988079], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_jump_over_wall_block', {
    description: 'walls: hold forward, wait 5, jump 1 ticks, until onGround, wait 5, release all, until still',
    steps: [hold('forward'), ticks(5), press('jump', 1), until('onGround', 40), ticks(5), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 1720.6711080113648], onGround: true },
          'leaves the ground (2)': { tick: 6, pos: [0.5, 101.41999998688698, 1721.431529191284], vel: [0, 0.33319999363422365, 0.11329713520754602], onGround: false },
          'top speed 4.15 b/s': { tick: 6, pos: [0.5, 101.41999998688698, 1721.431529191284], vel: [0, 0.33319999363422365, 0.11329713520754602] },
          'peak height 1.252': { tick: 11, pos: [0.5, 102.25220334025373, 1722.1658359674395] },
          'touches a wall': { tick: 16, pos: [0.5, 101.1212968405392, 1722.949999988079], isCollidedHorizontally: true },
          'lands (2)': { tick: 17, pos: [0.5, 101, 1722.949999988079], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_sprint_10deg', {
    description: 'walls: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.06850415249759495, -0.0784000015258789, 0.012076120469547445] },
          'leaves the ground (1)': { tick: 1, pos: [8.625465466191681, 101, 1717.5221174341884], vel: [0.06850415249759495, -0.0784000015258789, 0.012076120469547445], onGround: false },
          'lands (1)': { tick: 2, pos: [8.7190627086918, 101, 1717.5386170409251], onGround: true },
          'top speed 5.612 b/s': { tick: 27, pos: [15.48320449230986, 101, 1718.731020538727], vel: [0.1508902071366299, -0.0784000015258789, 0.026599384893067363] },
          'touches a wall': { tick: 28, pos: [15.699999988079071, 101, 1718.7797373578085], isCollidedHorizontally: true },
          'final state': { tick: 47, pos: [15.699999988079071, 101, 1719.295255463164], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_sprint_1deg', {
    description: 'walls: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.06954982565508333, -0.0784000015258789, 0.001213700266995467] },
          'leaves the ground (1)': { tick: 1, pos: [8.627380618272323, 101, 1717.5022228940038], vel: [0.06954982565508333, -0.0784000015258789, 0.001213700266995467], onGround: false },
          'lands (1)': { tick: 2, pos: [8.722406564296664, 101, 1717.5038811730142], onGround: true },
          'top speed 5.612 b/s': { tick: 27, pos: [15.589798753017151, 101, 1717.6237226773535], vel: [0.15319345202877238, -0.0784000015258789, 0.00267334866590983] },
          'touches a wall': { tick: 28, pos: [15.699999988079071, 101, 1717.6286189200232], isCollidedHorizontally: true },
          'final state': { tick: 43, pos: [15.699999988079071, 101, 1717.6496509159483], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_sprint_45deg', {
    description: 'walls: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.049191358493453366, -0.0784000015258789, 0.04918192606176769] },
          'leaves the ground (1)': { tick: 1, pos: [8.59009405271016, 101, 1717.5900767771964], vel: [0.049191358493453366, -0.0784000015258789, 0.04918192606176769], onGround: false },
          'lands (1)': { tick: 2, pos: [8.657304219422079, 101, 1717.6572740563743], onGround: true },
          'top speed 5.612 b/s': { tick: 38, pos: [15.697384775582528, 101, 1724.6960046787067], vel: [0.10835102501672621, -0.0784000015258789, 0.10833024873258112] },
          'touches a wall': { tick: 39, pos: [15.699999988079071, 101, 1724.8944117046356], isCollidedHorizontally: true },
          'final state': { tick: 49, pos: [15.699999988079071, 101, 1725.2799858084823], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_sprint_5deg', {
    description: 'walls: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.06929584654837147, -0.0784000015258789, 0.0060611132014666115] },
          'leaves the ground (1)': { tick: 1, pos: [8.626915455127246, 101, 1717.51110093864], vel: [0.06929584654837147, -0.0784000015258789, 0.0060611132014666115], onGround: false },
          'lands (1)': { tick: 2, pos: [8.721594389427858, 101, 1717.5193822392832], onGround: true },
          'top speed 5.612 b/s': { tick: 27, pos: [15.563908526304175, 101, 1718.11786025217], vel: [0.15263402667099604, -0.0784000015258789, 0.013350469907352952] },
          'touches a wall': { tick: 28, pos: [15.699999988079071, 101, 1718.1423116607173], isCollidedHorizontally: true },
          'final state': { tick: 46, pos: [15.699999988079071, 101, 1718.3993825819894], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_sprint_8deg', {
    description: 'walls: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0688837881788553, -0.0784000015258789, 0.00967859016633695] },
          'leaves the ground (1)': { tick: 1, pos: [8.626160769556451, 101, 1717.517726353557], vel: [0.0688837881788553, -0.0784000015258789, 0.00967859016633695], onGround: false },
          'lands (1)': { tick: 2, pos: [8.72027670839285, 101, 1717.5309502139776], onGround: true },
          'top speed 5.612 b/s': { tick: 27, pos: [15.521903950637023, 101, 1718.4866201079003], vel: [0.15172640909655985, -0.0784000015258789, 0.021318481022597913] },
          'touches a wall': { tick: 28, pos: [15.699999988079071, 101, 1718.52566494248], isCollidedHorizontally: true },
          'final state': { tick: 46, pos: [15.699999988079071, 101, 1718.9361644675635], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_sprint_head_on', {
    description: 'walls: forward+sprint 30 ticks, until still',
    steps: [press(['forward', 'sprint'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [8.627400012409687, 101, 1717.5], vel: [0.0695604148553142, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [8.722440426461233, 101, 1717.5], onGround: true },
          'top speed 5.612 b/s': { tick: 27, pos: [15.590878199268598, 101, 1717.5], vel: [0.15321677625888094, -0.0784000015258789, 0] },
          'touches a wall': { tick: 28, pos: [15.699999988079071, 101, 1717.5], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [15.699999988079071, 101, 1717.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_stairs_inner_corner', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [12.5, 101, 1722.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [12.5, 101, 1722.6711080113648], onGround: true },
          'top speed 4.309 b/s': { tick: 11, pos: [12.5, 101, 1724.501263819991], vel: [0, -0.0784000015258789, 0.11763769845470062] },
          'touches a wall': { tick: 12, pos: [12.5, 101, 1724.699999988079], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [12.5, 101, 1724.699999988079], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_stairs_outer_corner', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [12.5, 101, 1725.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [12.5, 101, 1725.6711080113648], onGround: true },
          'top speed 4.226 b/s': { tick: 7, pos: [12.5, 101, 1726.6428263298592], vel: [0, -0.0784000015258789, 0.11536825106238933] },
          'touches a wall': { tick: 8, pos: [12.5, 101, 1726.699999988079], isCollidedHorizontally: true },
          'final state': { tick: 33, pos: [12.5, 101, 1726.699999988079], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_trapdoor_open', {
    description: 'walls: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [9.5, 101, 1720.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [9.5, 101, 1720.6711080113648], onGround: true },
          'top speed 4.317 b/s': { tick: 30, pos: [9.5, 101, 1726.6020985330301], vel: [0, -0.0784000015258789, 0.11785906279261237] },
          'final state': { tick: 40, pos: [9.5, 101, 1726.8579446305625], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_wall_walk_89deg', {
    description: 'walls: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0009387447643764958, -0.0784000015258789, 0.053499773214591075] },
          'leaves the ground (1)': { tick: 1, pos: [15.501719312555565, 101, 1706.5979849212463], vel: [0.0009387447643764958, -0.0784000015258789, 0.053499773214591075], onGround: false },
          'lands (1)': { tick: 2, pos: [15.503001919818244, 101, 1706.67108167798], onGround: true },
          'top speed 4.317 b/s': { tick: 40, pos: [15.644925573388297, 101, 1714.759417898771], vel: [0.0020677200340700032, -0.0784000015258789, 0.11784092662022569] },
          'final state': { tick: 50, pos: [15.649414138704973, 101, 1715.0152246266632], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_jump_over_airborne_wall', {
    description: 'collisionWalls: hold forward, wait 10, jump 1 ticks, wait 20, release forward, until steady, wait 5',
    steps: [hold('forward'), ticks(10), press('jump', 1), ticks(20), release('forward'), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [-7.5, 101, 114.59800000336766], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [-7.5, 101, 114.67110801136488], onGround: true },
          'leaves the ground (2)': { tick: 11, pos: [-7.5, 101.41999998688698, 116.50126381999118], vel: [0, 0.33319999363422365, 0.11763769845470062], onGround: false },
          'top speed 4.309 b/s': { tick: 11, pos: [-7.5, 101.41999998688698, 116.50126381999118], vel: [0, 0.33319999363422365, 0.11763769845470062] },
          'touches a wall': { tick: 13, pos: [-7.5, 102.00133597911214, 116.69999998807907], isCollidedHorizontally: true },
          'peak height 1.252': { tick: 16, pos: [-7.5, 102.25220334025373, 116.69999998807907] },
          'lands (2)': { tick: 22, pos: [-7.5, 101, 116.69999998807907], onGround: true }
        }
      }
    ]
  })

  recorded('pb_wall_sprint_air', {
    description: 'collisionWalls: hold sprint+forward, jump 1 ticks, wait 20, release sprint+forward, until steady, wait 5',
    steps: [hold('sprint', 'forward'), press('jump', 1), ticks(20), release('sprint', 'forward'), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.17876042753918261, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-2.1725999875903126, 101.41999998688698, 114.5], vel: [0.17876042753918261, 0.33319999363422365, 0], onGround: false },
          'top speed 6.548 b/s': { tick: 1, pos: [-2.1725999875903126, 101.41999998688698, 114.5], vel: [0.17876042753918261, 0.33319999363422365, 0] },
          'peak height 1.252': { tick: 6, pos: [-1.0865204111618252, 102.25220334025373, 114.5] },
          'touches a wall': { tick: 10, pos: [-0.30000001192092896, 101.49520087700593, 114.5], isCollidedHorizontally: true },
          'lands (1)': { tick: 12, pos: [-0.30000001192092896, 101, 114.5], onGround: true },
          'final state': { tick: 36, pos: [-0.30000001192092896, 101, 114.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_wall_walk_angled_30', {
    description: 'collisionWalls: forward 25 ticks, until steady, wait 5',
    steps: [press('forward', 25), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.04633758397018331, -0.0784000015258789, -0.026756966910599703] },
          'leaves the ground (1)': { tick: 1, pos: [-2.4151326399488076, 101, 114.4509945717899], vel: [0.04633758397018331, -0.0784000015258789, -0.026756966910599703], onGround: false },
          'lands (1)': { tick: 2, pos: [-2.351821584600697, 101, 114.4144365196024], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [-0.39334995671987216, 101, 113.28354543610794], vel: [0.10200802773738571, -0.0784000015258789, -0.058903058574246346] },
          'touches a wall': { tick: 14, pos: [-0.30000001192092896, 101, 113.1756369493236], isCollidedHorizontally: true },
          'final state': { tick: 40, pos: [-0.30000001192092896, 101, 111.86480440167489], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_wall_walk_corner', {
    description: 'collisionWalls: forward 25 ticks, until steady, wait 5',
    steps: [press('forward', 25), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783224843167181, -0.0784000015258789, -0.03783950414789568] },
          'leaves the ground (1)': { tick: 1, pos: [7.569289824244243, 101, 99.43069688689975], vel: [0.03783224843167181, -0.0784000015258789, -0.03783950414789568], onGround: false },
          'lands (1)': { tick: 2, pos: [7.620980037008514, 101, 99.37899676064815], onGround: true },
          'top speed 4.29 b/s': { tick: 9, pos: [8.610541678212071, 101, 98.38924533483615], vel: [0.08280594233175097, -0.0784000015258789, -0.0828218233973528] },
          'touches a wall': { tick: 10, pos: [8.762637444788066, 101, 98.30000001192093], isCollidedHorizontally: true },
          'final state': { tick: 40, pos: [9.699999988079071, 101, 98.30000001192093], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_wall_walk_perp', {
    description: 'collisionWalls: forward 25 ticks, until steady, wait 5',
    steps: [press('forward', 25), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-2.4019999966323375, 101, 114.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [-2.3288919886351227, 101, 114.5], onGround: true },
          'top speed 4.309 b/s': { tick: 11, pos: [-0.4987361800088269, 101, 114.5], vel: [0.11763769845470062, -0.0784000015258789, 0] },
          'touches a wall': { tick: 12, pos: [-0.30000001192092896, 101, 114.5], isCollidedHorizontally: true },
          'final state': { tick: 40, pos: [-0.30000001192092896, 101, 114.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_wall_walk_thin_gap', {
    description: 'collisionWalls: forward 30 ticks, until steady, wait 5',
    steps: [press('forward', 30), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [-11.5, 101, 99.59800000336766], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [-11.5, 101, 99.67110801136488], onGround: true },
          'top speed 4.317 b/s': { tick: 30, pos: [-11.5, 101, 105.60209853303066], vel: [0, -0.0784000015258789, 0.11785906279261237] },
          'final state': { tick: 45, pos: [-11.5, 101, 105.85794463056315], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
