// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: ice', () => {
  recorded('pb_walk_on_blue_ice', {
    description: 'blueIceSurface: forward 30 ticks, until steady, wait 5',
    steps: [press('forward', 30), stable(15), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.019693761928400874] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 424.52188220029444], vel: [0, -0.0784000015258789, 0.019693761928400874], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 424.5611759621662], onGround: true },
          'top speed 4.189 b/s': { tick: 30, pos: [0.5, 101, 429.160443534867], vel: [0, -0.0784000015258789, 0.18848628465563502] },
          'final state': { tick: 50, pos: [0.5, 101, 430.8160366752068], vel: [0, -0.0784000015258789, 0.02291045141538343], onGround: true }
        }
      }
    ]
  })

  recorded('pb_walk_on_ice', {
    description: 'iceSurface: forward 30 ticks, until steady, wait 5',
    steps: [press('forward', 30), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.02005714406293894] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 336.52249062909743], vel: [0, -0.0784000015258789, 0.02005714406293894], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 336.56214777310373], onGround: true },
          'top speed 4.022 b/s': { tick: 30, pos: [0.5, 101, 341.05846178447746], vel: [0, -0.0784000015258789, 0.17932464746641621] },
          'final state': { tick: 45, pos: [0.5, 101, 342.41834900086616], vel: [0, -0.0784000015258789, 0.032184913163226275], onGround: true }
        }
      }
    ]
  })

  recorded('pb_walk_on_packed_ice', {
    description: 'packedIceSurface: forward 30 ticks, until steady, wait 5',
    steps: [press('forward', 30), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.02005714406293894] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 380.52249062909743], vel: [0, -0.0784000015258789, 0.02005714406293894], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 380.56214777310373], onGround: true },
          'top speed 4.022 b/s': { tick: 30, pos: [0.5, 101, 385.05846178447746], vel: [0, -0.0784000015258789, 0.17932464746641621] },
          'final state': { tick: 45, pos: [0.5, 101, 386.41834900086616], vel: [0, -0.0784000015258789, 0.032184913163226275], onGround: true }
        }
      }
    ]
  })
})
