// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: jump', () => {
  recorded('pb_jump_into_ceiling', {
    description: 'ceilingRoom: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(10), ticks(5)],
    groups: [
      {
        versions: ['1.7.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.14.4', '1.15', '1.16'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.17'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20.4', '1.20.5', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.1'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'peak height 0.2': { tick: 1, pos: [-4.5, 101.20000004768372, 287.5] },
          'lands (1)': { tick: 3, pos: [-4.5, 101, 287.5], onGround: true },
          'final state': { tick: 16, pos: [-4.5, 101, 287.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_jump_out_of_pit', {
    description: 'flatPit: jump 1 ticks, until steady, wait 5',
    steps: [press('jump', 1), stable(15), ticks(5)],
    groups: [
      {
        versions: ['1.7.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 97.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.249': { tick: 5, pos: [-0.5, 98.24918707874468, 1106.5] },
          'lands (1)': { tick: 14, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.8.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 96.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.249': { tick: 5, pos: [-0.5, 97.24918707874468, 1106.5] },
          'lands (1)': { tick: 12, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 96.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 97.25220334025373, 1106.5] },
          'lands (1)': { tick: 12, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.14.4', '1.15', '1.16'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 97.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 98.25220334025373, 1106.5] },
          'lands (1)': { tick: 14, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.17'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 96.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 97.25220334025373, 1106.5] },
          'lands (1)': { tick: 12, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 97.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 98.25220334025373, 1106.5] },
          'lands (1)': { tick: 14, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 96.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 97.25220334025373, 1106.5] },
          'lands (1)': { tick: 12, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20.4', '1.20.5', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 97.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 98.25220334025373, 1106.5] },
          'lands (1)': { tick: 14, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 96.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 97.25220334025373, 1106.5] },
          'lands (1)': { tick: 12, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.1'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [-0.5, 97.41999998688698, 1106.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [-0.5, 98.25220334025373, 1106.5] },
          'lands (1)': { tick: 14, pos: [-0.5, 96, 1106.5], onGround: true },
          'final state': { tick: 21, pos: [-0.5, 96, 1106.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
