// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: powder_snow', () => {
  recorded('pb_jump_out_of_powder_snow', {
    description: 'powderSnowField: jump 40 ticks, until steady, wait 5',
    steps: [press('jump', 40), stable(15), ticks(5)],
    groups: [
      {
        versions: ['1.17', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.20.5', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 99.41999998688698, 920.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 99.91979997733831, 920.5], isInWeb: true },
          'peak height 0.92': { tick: 2, pos: [0.5, 99.91979997733831, 920.5] },
          'lands (1)': { tick: 36, pos: [0.5, 96, 920.5], onGround: true },
          'leaves the ground (2)': { tick: 37, pos: [0.5, 96.62999998033047, 920.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 43, pos: [0.5, 96, 920.5], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 920.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_sink_in_powder_snow', {
    description: 'powderSnowField: wait 50, until steady, wait 5',
    steps: [ticks(50), stable(15), ticks(5)],
    groups: [
      {
        versions: ['1.17', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.20.5', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 99, 920.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 98.88239999771118, 920.5], isInWeb: true },
          'lands (1)': { tick: 27, pos: [0.5, 96, 920.5], onGround: true },
          'final state': { tick: 70, pos: [0.5, 96, 920.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_walk_into_powder_snow', {
    description: 'powderSnowField: forward 40 ticks, until steady, wait 5',
    steps: [press('forward', 40), stable(15), ticks(5)],
    groups: [
      {
        versions: ['1.17'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 4.316 b/s': { tick: 13, pos: [0.5, 101, 915.0466658857051], vel: [0, -0.0784000015258789, 0.11781389317747222] },
          'enters a slowing block': { tick: 14, pos: [0.5, 101, 915.2405833868141], isInWeb: true },
          'leaves the ground (1)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4154083850221], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 58, pos: [0.5, 96, 915.8387683725837], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8387683725837], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.313 b/s': { tick: 12, pos: [0.5, 101, 914.7169015218135], vel: [0, -0.0784000015258789, 0.1177381988706114] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3405715261398], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4278265249258], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8511865124873], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8511865124873], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['22w19a'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 914.9326397240518], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3415215346567], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4287765334427], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8521365210042], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8521365210042], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.316 b/s': { tick: 14, pos: [0.5, 101, 915.1484327995236], vel: [0, -0.0784000015258789, 0.11782303289302208] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3423585263764], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4299285257985], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.85328851336], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.85328851336], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 914.9326397240518], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3415215346567], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4287765334427], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8521365210042], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8521365210042], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20', '1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 4.316 b/s': { tick: 13, pos: [0.5, 101, 915.0466658857051], vel: [0, -0.0784000015258789, 0.11781389317747222] },
          'enters a slowing block': { tick: 14, pos: [0.5, 101, 915.2405833868141], isInWeb: true },
          'leaves the ground (1)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4154083850221], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 58, pos: [0.5, 96, 915.8387683725837], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8387683725837], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20.5', '1.21', '1.21.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 914.9326397240518], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3415215346567], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4287765334427], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8521365210042], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8521365210042], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.5'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.313 b/s': { tick: 12, pos: [0.5, 101, 914.7169015218135], vel: [0, -0.0784000015258789, 0.1177381988706114] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.340886526776], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.428141525562], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8515015131235], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8515015131235], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.6', '1.21.7'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 914.9326397240518], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3415215346567], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4287765334427], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8521365210042], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8521365210042], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.8'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 914.9326397240518], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3418365352929], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4290915340789], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8524515216404], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8524515216404], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.316 b/s': { tick: 14, pos: [0.5, 101, 915.1484327995236], vel: [0, -0.0784000015258789, 0.11782303289302208] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3423585263764], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4299285257985], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.85328851336], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.85328851336], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 4.316 b/s': { tick: 13, pos: [0.5, 101, 915.0466658857051], vel: [0, -0.0784000015258789, 0.11781389317747222] },
          'enters a slowing block': { tick: 14, pos: [0.5, 101, 915.2405833868141], isInWeb: true },
          'leaves the ground (1)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4157233856583], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 58, pos: [0.5, 96, 915.8390833732199], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8390833732199], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 4.314 b/s': { tick: 12, pos: [0.5, 101, 914.8308895496372], vel: [0, -0.0784000015258789, 0.11777633270024773] },
          'enters a slowing block': { tick: 14, pos: [0.5, 101, 915.2400613957308], isInWeb: true },
          'leaves the ground (1)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4145713933027], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 58, pos: [0.5, 96, 915.8379313808642], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8379313808642], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.1'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 912.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 101, 912.6711080113649], onGround: true },
          'top speed 4.315 b/s': { tick: 13, pos: [0.5, 101, 914.9326397240518], vel: [0, -0.0784000015258789, 0.11779307210407237] },
          'enters a slowing block': { tick: 15, pos: [0.5, 101, 915.3415215346567], isInWeb: true },
          'leaves the ground (2)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4287765334427], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (2)': { tick: 58, pos: [0.5, 96, 915.8521365210042], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8521365210042], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 4.316 b/s': { tick: 13, pos: [0.5, 101, 915.0466658857051], vel: [0, -0.0784000015258789, 0.11781389317747222] },
          'enters a slowing block': { tick: 14, pos: [0.5, 101, 915.2405833868141], isInWeb: true },
          'leaves the ground (1)': { tick: 16, pos: [0.5, 100.88239999771118, 915.4157233856583], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 58, pos: [0.5, 96, 915.8390833732199], onGround: true },
          'final state': { tick: 60, pos: [0.5, 96, 915.8390833732199], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
