// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*.pfix. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: slowdown', () => {
  recorded('b_berry_jump_inside', {
    description: 'berryBushField: jump 1 ticks, wait 40, until steady',
    steps: [press('jump', 1), ticks(40), stable(5, 200)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 883.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 101.66989998211264, 883.5], isInWeb: true },
          'peak height 0.67': { tick: 2, pos: [0.5, 101.66989998211264, 883.5] },
          'lands (1)': { tick: 14, pos: [0.5, 101, 883.5], onGround: true },
          'final state': { tick: 46, pos: [0.5, 101, 883.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_berry_sneak_inside', {
    description: 'berryBushField: forward+sneak 40 ticks, until steady',
    steps: [press(['forward', 'sneak'], 40), stable(5, 200)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 883.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 101, 883.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 101, 883.6455104108866], onGround: true },
          'enters a slowing block': { tick: 2, pos: [0.5, 101, 883.6455104108866], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 884.5392705273982], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_berry_sprint_in', {
    description: 'berryBushField: forward+sprint 40 ticks, until steady',
    steps: [press(['forward', 'sprint'], 40), stable(5, 200)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 877.9694807464659], vel: [0, -0.0784000015258789, 0.1528560218142385] },
          'enters a slowing block': { tick: 11, pos: [0.5, 101, 878.193685577186], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 881.1493659091348], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_berry_walk_in_diagonal', {
    description: 'berryBushField: forward 60 ticks, until steady',
    steps: [press('forward', 60), stable(5, 200)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 877.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 17, pos: [-0.11928382255976955, 101, 877.8807161774403], isInWeb: true },
          'final state': { tick: 65, pos: [2.2645146348173273, 101, 880.2645146348151], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783224843167181] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 877.7583955384313], vel: [0.08333374355336566, -0.0784000015258789, 0.08332575668611987] },
          'enters a slowing block': { tick: 17, pos: [-0.11928382255976955, 101, 877.8804880049948], isInWeb: true },
          'final state': { tick: 65, pos: [2.2645146348173273, 101, 880.2640579945128], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_cobweb_jump_inside', {
    description: 'cobwebField: jump 1 ticks, wait 40, until steady',
    steps: [press('jump', 1), ticks(40), stable(5, 200)],
    groups: [
      {
        versions: ['1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 846.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 101.43665998681695, 846.5], isInWeb: true },
          'peak height 0.437': { tick: 2, pos: [0.5, 101.43665998681695, 846.5] },
          'final state': { tick: 46, pos: [0.5, 101.2641799808896, 846.5], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      }
    ]
  })

  recorded('b_cobweb_sneak_inside', {
    description: 'cobwebField: forward+sneak 40 ticks, until steady',
    steps: [press(['forward', 'sneak'], 40), stable(5, 200)],
    groups: [
      {
        versions: ['1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.016052401037907504] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 846.529399998486], vel: [0, -0.0784000015258789, 0.016052401037907504], onGround: false },
          'top speed 0.588 b/s': { tick: 1, pos: [0.5, 101, 846.529399998486], vel: [0, -0.0784000015258789, 0.016052401037907504] },
          'lands (1)': { tick: 2, pos: [0.5, 101, 846.5348830988794], onGround: true },
          'enters a slowing block': { tick: 2, pos: [0.5, 101, 846.5348830988794], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 846.8141830844968], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 846.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 101, 846.5980000033677], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 101, 846.6128470054962], onGround: true },
          'enters a slowing block': { tick: 2, pos: [0.5, 101, 846.6128470054962], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 846.8921470377447], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_cobweb_sprint_in', {
    description: 'cobwebField: forward+sprint 40 ticks, until steady',
    steps: [press(['forward', 'sprint'], 40), stable(5, 200)],
    groups: [
      {
        versions: ['1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956039771757005] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 840.9694801380546], vel: [0, -0.0784000015258789, 0.15285598415478233] },
          'enters a slowing block': { tick: 11, pos: [0.5, 101, 841.0395441293488], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 841.9631939917574], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.06956040585360501] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 840.9694804268939], vel: [0, -0.0784000015258789, 0.15285600203336944] },
          'enters a slowing block': { tick: 11, pos: [0.5, 101, 841.039544426383], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 841.9631943968251], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 840.9694807464659], vel: [0, -0.0784000015258789, 0.1528560218142385] },
          'enters a slowing block': { tick: 11, pos: [0.5, 101, 841.0395447550219], isInWeb: true },
          'final state': { tick: 45, pos: [0.5, 101, 841.9631948449937], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_cobweb_walk_in_diagonal', {
    description: 'cobwebField: forward 60 ticks, until steady',
    steps: [press('forward', 60), stable(5, 200)],
    groups: [
      {
        versions: ['1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783586984762133, -0.0784000015258789, 0.03783586984762133] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138828119466718, 101, 840.7586117188055], vel: [0.0833337328767186, -0.0784000015258789, 0.0833337328767186] },
          'enters a slowing block': { tick: 17, pos: [-0.20323073375713333, 101, 840.796769266243], isInWeb: true },
          'final state': { tick: 65, pos: [0.5417061776320984, 101, 841.5417061776322], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 840.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 17, pos: [-0.2032304394970056, 101, 840.796769560503], isInWeb: true },
          'final state': { tick: 65, pos: [0.5417065673329106, 101, 841.5417065673311], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783224843167181] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 840.7583955384313], vel: [0.08333374355336566, -0.0784000015258789, 0.08332575668611987] },
          'enters a slowing block': { tick: 17, pos: [-0.2032304394970056, 101, 840.7965494336638], isInWeb: true },
          'final state': { tick: 65, pos: [0.5417065673329106, 101, 841.5414150442884], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_powder_snow_jump_inside', {
    description: 'powderSnowField: jump 1 ticks, wait 40, until steady',
    steps: [press('jump', 1), ticks(40), stable(5, 200)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 920.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 101.91979997733831, 920.5], isInWeb: true },
          'peak height 0.92': { tick: 2, pos: [0.5, 101.91979997733831, 920.5] },
          'final state': { tick: 46, pos: [0.5, 96.74539987663003, 920.5], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      }
    ]
  })

  recorded('b_powder_snow_sneak_inside', {
    description: 'powderSnowField: forward+sneak 40 ticks, until steady',
    steps: [press(['forward', 'sneak'], 40), stable(5, 200)],
    groups: [
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 920.5], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 100.88239999771118, 920.5534492062465], isInWeb: true },
          'top speed 1.069 b/s': { tick: 2, pos: [0.5, 100.88239999771118, 920.5534492062465], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 44, pos: [0.5, 96, 920.754545216647], onGround: true },
          'final state': { tick: 45, pos: [0.5, 96, 920.754545216647], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.3', '1.21.4', '1.21.5', '1.21.6'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053316907640648066] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 920.5], vel: [0, -0.0784000015258789, 0.053316907640648066], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 100.88239999771118, 920.5532772158791], isInWeb: true },
          'top speed 1.066 b/s': { tick: 2, pos: [0.5, 100.88239999771118, 920.5532772158791], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 44, pos: [0.5, 96, 920.7543732262797], onGround: true },
          'final state': { tick: 45, pos: [0.5, 96, 920.7543732262797], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.7'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 920.5], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 100.88239999771118, 920.5534492062465], isInWeb: true },
          'top speed 1.069 b/s': { tick: 2, pos: [0.5, 100.88239999771118, 920.5534492062465], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 44, pos: [0.5, 96, 920.754545216647], onGround: true },
          'final state': { tick: 45, pos: [0.5, 96, 920.754545216647], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053316907640648066] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 920.5], vel: [0, -0.0784000015258789, 0.053316907640648066], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 100.88239999771118, 920.5532772158791], isInWeb: true },
          'top speed 1.066 b/s': { tick: 2, pos: [0.5, 100.88239999771118, 920.5532772158791], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 44, pos: [0.5, 96, 920.7543732262797], onGround: true },
          'final state': { tick: 45, pos: [0.5, 96, 920.7543732262797], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 920.5], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'enters a slowing block': { tick: 2, pos: [0.5, 100.88239999771118, 920.5534492062465], isInWeb: true },
          'top speed 1.069 b/s': { tick: 2, pos: [0.5, 100.88239999771118, 920.5534492062465], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 44, pos: [0.5, 96, 920.754545216647], onGround: true },
          'final state': { tick: 45, pos: [0.5, 96, 920.754545216647], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('b_powder_snow_sprint_in', {
    description: 'powderSnowField: forward+sprint 40 ticks, until steady',
    steps: [press(['forward', 'sprint'], 40), stable(5, 200)],
    groups: [
      {
        versions: ['1.18'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5017051122741], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6155461121799], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.234710076247], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['22w19a'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5017051122741], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6155461121799], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2347101206019], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.19'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 914.9694807464659], vel: [0, -0.0784000015258789, 0.1528560218142385] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5006170143081], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6144580142139], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2336220226359], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5017051122741], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6159556162926], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2351196247146], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5021146163868], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6163651204054], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2355290844724], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.20.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5021146163868], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6167746245181], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2359385885852], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.21'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5021146163868], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6159556162927], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2351195803598], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 914.9694807464659], vel: [0, -0.0784000015258789, 0.1528560218142385] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5010265184208], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6144580142139], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.233621978281], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5021146163868], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6159556162927], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2351195803598], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 914.9694807464659], vel: [0, -0.0784000015258789, 0.1528560218142385] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5010265184208], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.614048523244], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2332124873111], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.605 b/s': { tick: 11, pos: [0.5, 101, 915.2497367806899], vel: [0, -0.0784000015258789, 0.15301981245991675] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5021146163868], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.6151366212101], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2343005852772], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      },
      {
        versions: ['26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'top speed 5.599 b/s': { tick: 10, pos: [0.5, 101, 914.9694807464659], vel: [0, -0.0784000015258789, 0.1528560218142385] },
          'enters a slowing block': { tick: 12, pos: [0.5, 101, 915.5010265184208], isInWeb: true },
          'leaves the ground (1)': { tick: 13, pos: [0.5, 100.88239999771118, 915.614048523244], vel: [0, -0.0784000015258789, 0], onGround: false },
          'final state': { tick: 45, pos: [0.5, 97.11919992446879, 916.2332124873111], vel: [0, -0.0784000015258789, 0], onGround: false }
        }
      }
    ]
  })

  recorded('b_powder_snow_walk_in_diagonal', {
    description: 'powderSnowField: forward 60 ticks, until steady',
    steps: [press('forward', 60), stable(5, 200)],
    groups: [
      {
        versions: ['1.18'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 19, pos: [0.1999816562356644, 101, 915.1999816562358], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.38396376630601264, 100.88239999771118, 915.3839637663061], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8579515618332825, 96, 915.8579515618321], onGround: true },
          'final state': { tick: 65, pos: [0.8579515618332825, 96, 915.8579515618321], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['22w19a'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 17, pos: [-0.08875778251826627, 101, 914.9112422174818], vel: [0.08333610396022968, -0.0784000015258789, 0.08333610396022968] },
          'enters a slowing block': { tick: 19, pos: [0.2004306746065726, 101, 915.2004306746067], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.38485825819440894, 100.88239999771118, 915.3848582581945], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8588460537216788, 96, 915.8588460537205], onGround: true },
          'final state': { tick: 65, pos: [0.8588460537216788, 96, 915.8588460537205], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 17, pos: [-0.08875778251826627, 101, 914.9112422174818], vel: [0.08333610396022968, -0.0784000015258789, 0.08333610396022968] },
          'enters a slowing block': { tick: 19, pos: [0.20006157117808201, 101, 915.2000615711781], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3844891547659184, 100.88239999771118, 915.384489154766], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8584769502931882, 96, 915.858476950292], onGround: true },
          'final state': { tick: 65, pos: [0.8584769502931882, 96, 915.858476950292], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 18, pos: [0.06387478719358353, 101, 915.0638747871936], vel: [0.08333739274252713, -0.0784000015258789, 0.08333739274252713] },
          'enters a slowing block': { tick: 19, pos: [0.2007997780350632, 101, 915.2007997780352], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3854501007049886, 100.88239999771118, 915.3854501007052], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8594378962322584, 96, 915.8594378962312], onGround: true },
          'final state': { tick: 65, pos: [0.8594378962322584, 96, 915.8594378962312], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 19, pos: [0.19961255280717383, 101, 915.1996125528073], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.38359466287752203, 100.88239999771118, 915.3835946628776], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8575824584047919, 96, 915.8575824584036], onGround: true },
          'final state': { tick: 65, pos: [0.8575824584047919, 96, 915.8575824584036], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20.4', '1.21'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 17, pos: [-0.08875778251826627, 101, 914.9112422174818], vel: [0.08333610396022968, -0.0784000015258789, 0.08333610396022968] },
          'enters a slowing block': { tick: 19, pos: [0.2004306746065726, 101, 915.2004306746067], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.38485825819440894, 100.88239999771118, 915.3848582581945], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8588460537216788, 96, 915.8588460537205], onGround: true },
          'final state': { tick: 65, pos: [0.8588460537216788, 96, 915.8588460537205], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 19, pos: [0.1999816562356644, 101, 915.1999816562358], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3844092398235008, 100.88239999771118, 915.3844092398235], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8583970353507706, 96, 915.8583970353495], onGround: true },
          'final state': { tick: 65, pos: [0.8583970353507706, 96, 915.8583970353495], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 19, pos: [0.1997589171535754, 101, 915.1997589171536], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3839637616593227, 100.88239999771118, 915.3839637616594], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8579515571865926, 96, 915.8579515571854], onGround: true },
          'final state': { tick: 65, pos: [0.8579515571865926, 96, 915.8579515571854], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.5'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 18, pos: [0.06387478719358353, 101, 915.0638747871936], vel: [0.08333739274252713, -0.0784000015258789, 0.08333739274252713] },
          'enters a slowing block': { tick: 19, pos: [0.20057703895297416, 101, 915.200577038953], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.38522736162289956, 100.88239999771118, 915.385227361623], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8592151571501694, 96, 915.859215157149], onGround: true },
          'final state': { tick: 65, pos: [0.8592151571501694, 96, 915.859215157149], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.6', '1.21.7', '1.21.8'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 19, pos: [0.1997589171535754, 101, 915.1997589171536], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3839637616593227, 100.88239999771118, 915.3839637616594], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8579515571865926, 96, 915.8579515571854], onGround: true },
          'final state': { tick: 65, pos: [0.8579515571865926, 96, 915.8579515571854], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.9'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 18, pos: [0.06387478719358353, 101, 915.0638747871936], vel: [0.08333739274252713, -0.0784000015258789, 0.08333739274252713] },
          'enters a slowing block': { tick: 19, pos: [0.2007997780350632, 101, 915.2007997780352], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3856728397870776, 100.88239999771118, 915.3856728397872], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8596606353143474, 96, 915.8596606353132], onGround: true },
          'final state': { tick: 65, pos: [0.8596606353143474, 96, 915.8596606353132], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783587469512084] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7586120081768], vel: [0.08333374355336566, -0.0784000015258789, 0.08333374355336566] },
          'enters a slowing block': { tick: 19, pos: [0.1997589171535754, 101, 915.1997589171536], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3839637616593227, 100.88239999771118, 915.3839637616594], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8579515571865926, 96, 915.8579515571854], onGround: true },
          'final state': { tick: 65, pos: [0.8579515571865926, 96, 915.8579515571854], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03783587469512084, -0.0784000015258789, 0.03783224843167181] },
          'top speed 4.317 b/s': { tick: 16, pos: [-0.24138799182325205, 101, 914.7583955384313], vel: [0.08333374355336566, -0.0784000015258789, 0.08332575668611987] },
          'enters a slowing block': { tick: 19, pos: [0.1997589171535754, 101, 915.1995001670346], isInWeb: true },
          'leaves the ground (1)': { tick: 22, pos: [0.3839637616593227, 100.88239999771118, 915.3836873569915], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 64, pos: [0.8579515571865926, 96, 915.8576297246113], onGround: true },
          'final state': { tick: 65, pos: [0.8579515571865926, 96, 915.8576297246113], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
