// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stopped, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: sneak', () => {
  recorded('g_edge_sneak_b', {
    description: 'ledges: back+sneak 40 ticks, wait 5',
    steps: [press(['back', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 102, 1669.4019999966324], vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'leaves the ground (1)': { tick: 42, pos: [0.5, 101.92159999847412, 1667.658899754508], vel: [0, -0.1552320045166016, -0.010540705213844809], onGround: false },
          'final state': { tick: 45, pos: [0.5, 101.23152379758702, 1667.6300382487825], vel: [0, -0.37663049823865513, -0.007943170455464632], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_bl', {
    description: 'ledges: back+left+sneak 40 ticks, wait 5',
    steps: [press(['back', 'left', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.5707106720016997, 102, 1669.4292893279983], vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 42, pos: [2.345749306364887, 101.92159999847412, 1667.654250693635], vel: [0.010540705213594726, -0.1552320045166016, -0.010540705213594726], onGround: false },
          'final state': { tick: 45, pos: [2.374610812089794, 101.23152379758702, 1667.6253891879103], vel: [0.007943170455276176, -0.37663049823865513, -0.007943170455276176], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_br', {
    description: 'ledges: back+right+sneak 40 ticks, wait 5',
    steps: [press(['back', 'right', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.42928932799830033, 102, 1669.4292893279983], vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 42, pos: [-1.345749306364887, 101.92159999847412, 1667.654250693635], vel: [-0.010540705213594726, -0.1552320045166016, -0.010540705213594726], onGround: false },
          'final state': { tick: 45, pos: [-1.3746108120897944, 101.23152379758702, 1667.6253891879103], vel: [-0.007943170455276176, -0.37663049823865513, -0.007943170455276176], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_f', {
    description: 'ledges: forward+sneak 40 ticks, wait 5',
    steps: [press(['forward', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 102, 1669.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 42, pos: [0.5, 101.92159999847412, 1671.341100245492], vel: [0, -0.1552320045166016, 0.010540705213844809], onGround: false },
          'final state': { tick: 45, pos: [0.5, 101.23152379758702, 1671.3699617512175], vel: [0, -0.37663049823865513, 0.007943170455464632], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_fl', {
    description: 'ledges: forward+left+sneak 40 ticks, wait 5',
    steps: [press(['forward', 'left', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.5707106720016997, 102, 1669.5707106720017], vel: [0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'leaves the ground (1)': { tick: 42, pos: [2.345749306364887, 101.92159999847412, 1671.345749306365], vel: [0.010540705213594726, -0.1552320045166016, 0.010540705213594726], onGround: false },
          'final state': { tick: 45, pos: [2.374610812089794, 101.23152379758702, 1671.3746108120897], vel: [0.007943170455276176, -0.37663049823865513, 0.007943170455276176], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_fr', {
    description: 'ledges: forward+right+sneak 40 ticks, wait 5',
    steps: [press(['forward', 'right', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.42928932799830033, 102, 1669.5707106720017], vel: [-0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'leaves the ground (1)': { tick: 42, pos: [-1.345749306364887, 101.92159999847412, 1671.345749306365], vel: [-0.010540705213594726, -0.1552320045166016, 0.010540705213594726], onGround: false },
          'final state': { tick: 45, pos: [-1.3746108120897944, 101.23152379758702, 1671.3746108120897], vel: [-0.007943170455276176, -0.37663049823865513, 0.007943170455276176], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_l', {
    description: 'ledges: left+sneak 40 ticks, wait 5',
    steps: [press(['left', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 102, 1669.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 42, pos: [2.341100245492236, 101.92159999847412, 1669.5], vel: [0.010540705213844809, -0.1552320045166016, 0], onGround: false },
          'final state': { tick: 45, pos: [2.369961751217828, 101.23152379758702, 1669.5], vel: [0.007943170455464632, -0.37663049823865513, 0], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_r', {
    description: 'ledges: right+sneak 40 ticks, wait 5',
    steps: [press(['right', 'sneak'], 40), ticks(5)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.40199999663233754, 102, 1669.5], vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 42, pos: [-1.3411002454922363, 101.92159999847412, 1669.5], vel: [-0.010540705213844809, -0.1552320045166016, 0], onGround: false },
          'final state': { tick: 45, pos: [-1.3699617512178284, 101.23152379758702, 1669.5], vel: [-0.007943170455464632, -0.37663049823865513, 0], onGround: false }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_b', {
    description: 'ledges: back+sneak 30 ticks, until still',
    steps: [press(['back', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 102, 1669.4019999966324], vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'leaves the ground (1)': { tick: 32, pos: [0.5, 101.92159999847412, 1667.6588997538388], vel: [0, -0.1552320045166016, -0.010540705342917135], onGround: false },
          'lands (1)': { tick: 36, pos: [0.5, 101, 1667.622095077207], onGround: true },
          'final state': { tick: 41, pos: [0.5, 101, 1667.6109201475028], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_bl', {
    description: 'ledges: back+left+sneak 30 ticks, until still',
    steps: [press(['back', 'left', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.5707106720016997, 102, 1669.4292893279983], vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 32, pos: [2.3457493064847537, 101.92159999847412, 1667.6542506935152], vel: [0.010540705236708683, -0.1552320045166016, -0.010540705236708683], onGround: false },
          'lands (1)': { tick: 36, pos: [2.3825539827456437, 101, 1667.617446017254], onGround: true },
          'final state': { tick: 42, pos: [2.395883780349881, 101, 1667.60411621965], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_br', {
    description: 'ledges: back+right+sneak 30 ticks, until still',
    steps: [press(['back', 'right', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.42928932799830033, 102, 1669.4292893279983], vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 32, pos: [-1.3457493064847539, 101.92159999847412, 1667.6542506935152], vel: [-0.010540705236708683, -0.1552320045166016, -0.010540705236708683], onGround: false },
          'lands (1)': { tick: 36, pos: [-1.3825539827456437, 101, 1667.617446017254], onGround: true },
          'final state': { tick: 42, pos: [-1.3958837803498811, 101, 1667.60411621965], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_f', {
    description: 'ledges: forward+sneak 30 ticks, until still',
    steps: [press(['forward', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 102, 1669.5980000033676], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 32, pos: [0.5, 101.92159999847412, 1671.3411002461612], vel: [0, -0.1552320045166016, 0.010540705342917135], onGround: false },
          'lands (1)': { tick: 36, pos: [0.5, 101, 1671.377904922793], onGround: true },
          'final state': { tick: 41, pos: [0.5, 101, 1671.3890798524972], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_fl', {
    description: 'ledges: forward+left+sneak 30 ticks, until still',
    steps: [press(['forward', 'left', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.5707106720016997, 102, 1669.5707106720017], vel: [0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'leaves the ground (1)': { tick: 32, pos: [2.3457493064847537, 101.92159999847412, 1671.3457493064848], vel: [0.010540705236708683, -0.1552320045166016, 0.010540705236708683], onGround: false },
          'lands (1)': { tick: 36, pos: [2.3825539827456437, 101, 1671.382553982746], onGround: true },
          'final state': { tick: 42, pos: [2.395883780349881, 101, 1671.39588378035], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_fr', {
    description: 'ledges: forward+right+sneak 30 ticks, until still',
    steps: [press(['forward', 'right', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'top speed 2 b/s': { tick: 1, pos: [0.42928932799830033, 102, 1669.5707106720017], vel: [-0.03860803139735231, -0.0784000015258789, 0.03860803139735231] },
          'leaves the ground (1)': { tick: 32, pos: [-1.3457493064847539, 101.92159999847412, 1671.3457493064848], vel: [-0.010540705236708683, -0.1552320045166016, 0.010540705236708683], onGround: false },
          'lands (1)': { tick: 36, pos: [-1.3825539827456437, 101, 1671.382553982746], onGround: true },
          'final state': { tick: 42, pos: [-1.3958837803498811, 101, 1671.39588378035], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_l', {
    description: 'ledges: left+sneak 30 ticks, until still',
    steps: [press(['left', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5980000033676625, 102, 1669.5], vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 32, pos: [2.341100246161592, 101.92159999847412, 1669.5], vel: [0.010540705342917135, -0.1552320045166016, 0], onGround: false },
          'lands (1)': { tick: 36, pos: [2.3779049227933267, 101, 1669.5], onGround: true },
          'final state': { tick: 41, pos: [2.3890798524976127, 101, 1669.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sneak_release_r', {
    description: 'ledges: right+sneak 30 ticks, until still',
    steps: [press(['right', 'sneak'], 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.40199999663233754, 102, 1669.5], vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 32, pos: [-1.3411002461615924, 101.92159999847412, 1669.5], vel: [-0.010540705342917135, -0.1552320045166016, 0], onGround: false },
          'lands (1)': { tick: 36, pos: [-1.3779049227933273, 101, 1669.5], onGround: true },
          'final state': { tick: 41, pos: [-1.3890798524976136, 101, 1669.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_b', {
    description: 'ledges: back+sprint 15 ticks, until still',
    steps: [press(['back', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, -0.053508008053839436] },
          'leaves the ground (1)': { tick: 11, pos: [0.5, 101.92159999847412, 1667.384817994356], vel: [0, -0.1552320045166016, -0.11770754062540936], onGround: false },
          'top speed 4.312 b/s': { tick: 11, pos: [0.5, 101.92159999847412, 1667.384817994356], vel: [0, -0.1552320045166016, -0.11770754062540936] },
          'lands (1)': { tick: 15, pos: [0.5, 101, 1666.7946824561259], onGround: true },
          'final state': { tick: 25, pos: [0.5, 101, 1666.4842709926525], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_bl', {
    description: 'ledges: back+left+sprint 15 ticks, until still',
    steps: [press(['back', 'left', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 14, pos: [2.4932326028721707, 101.92159999847412, 1667.5067673971278], vel: [0.08502193272932991, -0.1552320045166016, -0.08502193272932991], onGround: false },
          'top speed 4.404 b/s': { tick: 14, pos: [2.4932326028721707, 101.92159999847412, 1667.5067673971278], vel: [0.08502193272932991, -0.1552320045166016, -0.08502193272932991] },
          'lands (1)': { tick: 18, pos: [2.839480912266149, 101, 1667.160519087734], onGround: true },
          'final state': { tick: 27, pos: [2.9852960301511366, 101, 1667.014703969849], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_br', {
    description: 'ledges: back+right+sprint 15 ticks, until still',
    steps: [press(['back', 'right', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.03860803139735231, -0.0784000015258789, -0.03860803139735231] },
          'leaves the ground (1)': { tick: 14, pos: [-1.493232602872171, 101.92159999847412, 1667.5067673971278], vel: [-0.08502193272932991, -0.1552320045166016, -0.08502193272932991], onGround: false },
          'top speed 4.404 b/s': { tick: 14, pos: [-1.493232602872171, 101.92159999847412, 1667.5067673971278], vel: [-0.08502193272932991, -0.1552320045166016, -0.08502193272932991] },
          'lands (1)': { tick: 18, pos: [-1.8394809122661493, 101, 1667.160519087734], onGround: true },
          'final state': { tick: 27, pos: [-1.9852960301511375, 101, 1667.014703969849], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_f', {
    description: 'ledges: forward+sprint 15 ticks, until still',
    steps: [press(['forward', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.0695604148553142] },
          'leaves the ground (1)': { tick: 9, pos: [0.5, 101.92159999847412, 1671.6895246950746], vel: [0, -0.1552320045166016, 0.1525560389815397], onGround: false },
          'lands (1)': { tick: 13, pos: [0.5, 101, 1672.4550815773146], onGround: true },
          'top speed 6.26 b/s': { tick: 14, pos: [0.5, 101, 1672.7680575261666], vel: [0, -0.0784000015258789, 0.1708848879219715] },
          'final state': { tick: 25, pos: [0.5, 101, 1673.4198834184106], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_fl', {
    description: 'ledges: forward+left+sprint 15 ticks, until still',
    steps: [press(['forward', 'left', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.050190443980732705, -0.0784000015258789, 0.050190443980732705] },
          'leaves the ground (1)': { tick: 12, pos: [2.6863714539441745, 101.92159999847412, 1671.6863714539443], vel: [0.11047405133639175, -0.1552320045166016, 0.11047405133639175], onGround: false },
          'top speed 5.723 b/s': { tick: 12, pos: [2.6863714539441745, 101.92159999847412, 1671.6863714539443], vel: [0.11047405133639175, -0.1552320045166016, 0.11047405133639175] },
          'lands (1)': { tick: 16, pos: [3.221758361263319, 101, 1672.2217583612635], onGround: true },
          'final state': { tick: 26, pos: [3.4767025028541805, 101, 1672.4767025028546], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_fr', {
    description: 'ledges: forward+right+sprint 15 ticks, until still',
    steps: [press(['forward', 'right', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.050190443980732705, -0.0784000015258789, 0.050190443980732705] },
          'leaves the ground (1)': { tick: 12, pos: [-1.6863714539441743, 101.92159999847412, 1671.6863714539443], vel: [-0.11047405133639175, -0.1552320045166016, 0.11047405133639175], onGround: false },
          'top speed 5.723 b/s': { tick: 12, pos: [-1.6863714539441743, 101.92159999847412, 1671.6863714539443], vel: [-0.11047405133639175, -0.1552320045166016, 0.11047405133639175] },
          'lands (1)': { tick: 16, pos: [-2.221758361263319, 101, 1672.2217583612635], onGround: true },
          'final state': { tick: 26, pos: [-2.4767025028541805, 101, 1672.4767025028546], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_l', {
    description: 'ledges: left+sprint 15 ticks, until still',
    steps: [press(['left', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 11, pos: [2.615182005643896, 101.92159999847412, 1669.5], vel: [0.11770754062540936, -0.1552320045166016, 0], onGround: false },
          'top speed 4.312 b/s': { tick: 11, pos: [2.615182005643896, 101.92159999847412, 1669.5], vel: [0.11770754062540936, -0.1552320045166016, 0] },
          'lands (1)': { tick: 15, pos: [3.2053175438739845, 101, 1669.5], onGround: true },
          'final state': { tick: 25, pos: [3.5157290073472267, 101, 1669.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('g_edge_sprint_off_r', {
    description: 'ledges: right+sprint 15 ticks, until still',
    steps: [press(['right', 'sprint'], 15), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 11, pos: [-1.615182005643896, 101.92159999847412, 1669.5], vel: [-0.11770754062540936, -0.1552320045166016, 0], onGround: false },
          'top speed 4.312 b/s': { tick: 11, pos: [-1.615182005643896, 101.92159999847412, 1669.5], vel: [-0.11770754062540936, -0.1552320045166016, 0] },
          'lands (1)': { tick: 15, pos: [-2.205317543873984, 101, 1669.5], onGround: true },
          'final state': { tick: 25, pos: [-2.5157290073472263, 101, 1669.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('pb_sneak_to_edge', {
    description: 'sneakEdgePlatform: sneak+forward 80 ticks, wait 10',
    steps: [press(['sneak', 'forward'], 80), ticks(10)],
    groups: [
      {
        versions: ['1.7.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.016052401037907504] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 157.52939999848604], vel: [0, -0.0784000015258789, 0.016052401037907504], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 106, 157.55133240005935], onGround: true },
          'top speed 1.295 b/s': { tick: 29, pos: [0.5, 106, 159.26587169218215], vel: [0, -0.0784000015258789, 0.03535771524126811] },
          'leaves the ground (2)': { tick: 82, pos: [0.5, 105.92159999847412, 159.35005015211232], vel: [0, -0.1552320045166016, 0.010540703453729285], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.41209361318005], vel: [0, -0.7170746714356033, 0.00495679358478933], onGround: false }
        }
      },
      {
        versions: ['1.8.9', '1.9.4', '1.10.2', '1.11.2', '1.12.2', '1.13.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.016052401037907504] },
          'top speed 1.295 b/s': { tick: 28, pos: [0.5, 106, 159.23533557871153], vel: [0, -0.0784000015258789, 0.03535771492797964] },
          'leaves the ground (1)': { tick: 82, pos: [0.5, 105.92159999847412, 159.34902946736855], vel: [0, -0.1552320045166016, 0.010540703453729285], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.41107292843628], vel: [0, -0.7170746714356033, 0.00495679358478933], onGround: false }
        }
      },
      {
        versions: ['1.14.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.016052403717917444] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 157.52940000339447], vel: [0, -0.0784000015258789, 0.016052403717917444], onGround: false },
          'lands (1)': { tick: 2, pos: [0.5, 106, 157.55133240757223], onGround: true },
          'top speed 1.295 b/s': { tick: 29, pos: [0.5, 106, 159.26587198382475], vel: [0, -0.0784000015258789, 0.03535772114437424] },
          'leaves the ground (2)': { tick: 82, pos: [0.5, 105.92159999847412, 159.35005047450426], vel: [0, -0.1552320045166016, 0.010540705213540167], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.41209394593037], vel: [0, -0.7170746714356033, 0.004956794412345035], onGround: false }
        }
      },
      {
        versions: ['1.15', '1.16'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 106, 157.65738801188135], onGround: true },
          'leaves the ground (2)': { tick: 82, pos: [0.5, 105.92159999847412, 159.3516668471386], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.4137103185647], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      },
      {
        versions: ['1.17'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 82, pos: [0.5, 105.92159999847412, 159.34110024549062], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.40314371691673], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      },
      {
        versions: ['1.18', '22w19a', '1.19', '1.19.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 106, 157.65738801188135], onGround: true },
          'leaves the ground (2)': { tick: 82, pos: [0.5, 105.92159999847412, 159.3516668471386], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.4137103185647], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      },
      {
        versions: ['1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 82, pos: [0.5, 105.92159999847412, 159.34110024549062], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.40314371691673], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      },
      {
        versions: ['1.20.4', '1.20.5', '1.21', '1.21.3', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 106, 157.65738801188135], onGround: true },
          'leaves the ground (2)': { tick: 82, pos: [0.5, 105.92159999847412, 159.3516668471386], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.4137103185647], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 82, pos: [0.5, 105.92159999847412, 159.34110024549062], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.40314371691673], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      },
      {
        versions: ['26.1'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436], onGround: false },
          'top speed 1.96 b/s': { tick: 1, pos: [0.5, 106, 157.59800000336767], vel: [0, -0.0784000015258789, 0.053508008053839436] },
          'lands (1)': { tick: 2, pos: [0.5, 106, 157.65738801188135], onGround: true },
          'leaves the ground (2)': { tick: 82, pos: [0.5, 105.92159999847412, 159.3516668471386], vel: [0, -0.1552320045166016, 0.01054070521354017], onGround: false },
          'final state': { tick: 90, pos: [0.5, 102.6537296175886, 159.4137103185647], vel: [0, -0.7170746714356033, 0.004956794412345038], onGround: false }
        }
      }
    ]
  })
})
