// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (1ba1386) from test/fixtures/java/*.pfix. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, stable, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: enchant', () => {
  recorded('q_riptide_1_surface', {
    description: 'water: use 15 ticks, wait 60, until steady',
    steps: [press('use', 15), ticks(60), stable(5, 200)],
    groups: [
      {
        versions: ['1.13.2', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 3, pos: [0.5, 100.76636799395752, 1833.5], isInWater: true },
          'top speed 25.981 b/s': { tick: 16, pos: [1.799044132232666, 100.22021565189982, 1833.5], vel: [1.0392353212719456, 0.5636927217797392, 0] },
          'peak height 1.151': { tick: 23, pos: [6.448114702639576, 102.15124355164737, 1833.5] },
          'enters water (tick 29)': { tick: 29, pos: [8.44096005381233, 100.67128823799425, 1833.5], isInWater: true },
          'lands (1)': { tick: 32, pos: [9.016054496637507, 99.5, 1833.5], onGround: true },
          'final state': { tick: 80, pos: [9.605845463665096, 99.5, 1833.5], vel: [0, -0.005, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 4, pos: [0.5, 100.53584062504456, 1833.5], isInWater: true },
          'top speed 25.981 b/s': { tick: 16, pos: [1.799044132232666, 100.22021565189982, 1833.5], vel: [1.0392353212719456, 0.5636927217797392, 0] },
          'peak height 1.151': { tick: 23, pos: [6.448114702639576, 102.15124355164737, 1833.5] },
          'enters water (tick 30)': { tick: 30, pos: [8.6766544945992, 100.17182304958321, 1833.5], isInWater: true },
          'lands (1)': { tick: 32, pos: [9.016054496637507, 99.5, 1833.5], onGround: true },
          'final state': { tick: 80, pos: [9.605845463665096, 99.5, 1833.5], vel: [0, -0.005, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 3, pos: [0.5, 100.76636799395752, 1833.5], isInWater: true },
          'top speed 25.981 b/s': { tick: 16, pos: [1.799044132232666, 100.22021565189982, 1833.5], vel: [1.0392353212719456, 0.5636927217797392, 0] },
          'peak height 1.151': { tick: 23, pos: [6.448114702639576, 102.15124355164737, 1833.5] },
          'enters water (tick 29)': { tick: 29, pos: [8.44096005381233, 100.67128823799425, 1833.5], isInWater: true },
          'lands (1)': { tick: 32, pos: [9.016054496637507, 99.5, 1833.5], onGround: true },
          'final state': { tick: 80, pos: [9.605845463665096, 99.5, 1833.5], vel: [0, -0.005, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_riptide_1_underwater_level', {
    description: 'water: use 15 ticks, wait 60, until steady',
    steps: [press('use', 15), ticks(60), stable(5, 200)],
    groups: [
      {
        versions: ['1.13.2', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 99, 1833.5], vel: [0, -0.005, 0], onGround: false },
          'top speed 30 b/s': { tick: 16, pos: [2, 98.72148155259214, 1833.5], vel: [1.2000000178813934, -0.02429631383862434, 0] },
          'touches a wall': { tick: 21, pos: [5.699999988079071, 98.59884706160592, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 80, pos: [5.699999988079071, 97.12499989348328, 1833.5], vel: [0, -0.025000001048403896, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_riptide_3_surface', {
    description: 'water: use 15 ticks, wait 60, until steady',
    steps: [press('use', 15), ticks(60), stable(5, 200)],
    groups: [
      {
        versions: ['1.13.2', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 3, pos: [0.5, 100.76636799395752, 1833.5], isInWater: true },
          'top speed 51.962 b/s': { tick: 16, pos: [3.098088264465332, 100.97020528069163, 1833.5], vel: [2.0784706425438912, 1.1636844337537595, 0] },
          'peak height 7.721': { tick: 29, pos: [19.415177525008694, 108.7210704915401, 1833.5] },
          'lands (1)': { tick: 45, pos: [24.69355622555892, 101, 1833.5], onGround: true },
          'final state': { tick: 80, pos: [24.986349063156208, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 4, pos: [0.5, 100.53584062504456, 1833.5], isInWater: true },
          'top speed 51.962 b/s': { tick: 16, pos: [3.098088264465332, 100.97020528069163, 1833.5], vel: [2.0784706425438912, 1.1636844337537595, 0] },
          'peak height 7.721': { tick: 29, pos: [19.415177525008694, 108.7210704915401, 1833.5] },
          'lands (1)': { tick: 45, pos: [24.69355622555892, 101, 1833.5], onGround: true },
          'final state': { tick: 80, pos: [24.986349063156208, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 3, pos: [0.5, 100.76636799395752, 1833.5], isInWater: true },
          'top speed 51.962 b/s': { tick: 16, pos: [3.098088264465332, 100.97020528069163, 1833.5], vel: [2.0784706425438912, 1.1636844337537595, 0] },
          'peak height 7.721': { tick: 29, pos: [19.415177525008694, 108.7210704915401, 1833.5] },
          'lands (1)': { tick: 45, pos: [24.69355622555892, 101, 1833.5], onGround: true },
          'final state': { tick: 80, pos: [24.986349063156208, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('q_riptide_3_underwater_level', {
    description: 'water: use 15 ticks, wait 60, until steady',
    steps: [press('use', 15), ticks(60), stable(5, 200)],
    groups: [
      {
        versions: ['1.13.2', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3', '1.21.4', '1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.005, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 99, 1833.5], vel: [0, -0.005, 0], onGround: false },
          'top speed 60 b/s': { tick: 16, pos: [3.5, 98.72148155259214, 1833.5], vel: [2.400000035762787, -0.02429631383862434, 0] },
          'touches a wall': { tick: 17, pos: [5.699999988079071, 98.69718523875352, 1833.5], isCollidedHorizontally: true },
          'final state': { tick: 80, pos: [5.699999988079071, 97.12499989348328, 1833.5], vel: [0, -0.025000001048403896, 0], onGround: false }
        }
      }
    ]
  })

  recorded('q_riptide_short_charge', {
    description: 'water: use 5 ticks, wait 30',
    steps: [press('use', 5), ticks(30)],
    groups: [
      {
        versions: ['1.13.2', '1.18', '22w19a', '1.19', '1.19.2', '1.20', '1.20.4', '1.21', '1.21.2', '1.21.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 3, pos: [0.5, 100.76636799395752, 1833.5], isInWater: true },
          'final state': { tick: 35, pos: [0.5, 98.93954522612772, 1833.5], vel: [0, -0.025162837124435337, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.4'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 4, pos: [0.5, 100.53584062504456, 1833.5], isInWater: true },
          'final state': { tick: 35, pos: [0.5, 98.93954522612772, 1833.5], vel: [0, -0.025162837124435337, 0], onGround: false }
        }
      },
      {
        versions: ['1.21.5', '1.21.6', '1.21.7', '1.21.8', '1.21.9', '1.21.10', '1.21.11', '26.1', '26.2', '26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 1833.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'enters water': { tick: 3, pos: [0.5, 100.76636799395752, 1833.5], isInWater: true },
          'final state': { tick: 35, pos: [0.5, 98.93954522612772, 1833.5], vel: [0, -0.025162837124435337, 0], onGround: false }
        }
      }
    ]
  })
})
