// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, hold, press, release, stopped, ticks, until } = require('../../tools/java-harness')

describe('vanilla recordings: entity', () => {
  recorded('n_fall_onto_boat', {
    description: 'flat: until onGround, wait 20',
    steps: [until('onGround', 60), ticks(20)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 106, 38.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 12, pos: [0.5, 101.5625, 38.5], onGround: true },
          'final state': { tick: 32, pos: [0.5, 101.5625, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_jump_onto_boat', {
    description: 'flat: hold forward, wait 3, jump 1 ticks, until onGround, wait 10, release all, until still',
    steps: [hold('forward'), ticks(3), press('jump', 1), until('onGround', 40), ticks(10), release(), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 4, pos: [1.126906386248464, 101.41999998688698, 38.5], vel: [0.10738455387183765, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 9, pos: [1.8365138219838253, 102.25220334025373, 38.5] },
          'lands (1)': { tick: 13, pos: [2.5097942986110144, 101.5625, 38.5], onGround: true },
          'top speed 5.146 b/s': { tick: 14, pos: [2.767118979495944, 101.5625, 38.5], vel: [0.14049929208253353, -0.0784000015258789, 0] },
          'leaves the ground (2)': { tick: 19, pos: [3.8938628199759124, 101.48409999847412, 38.5], vel: [0.11895767680029329, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 22, pos: [4.330283605264377, 101, 38.5], onGround: true },
          'final state': { tick: 33, pos: [4.847050193174714, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_pushed_by_cow', {
    description: 'flat: wait 40',
    steps: [ticks(40)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [-0.031622777072899885, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101, 38.5], vel: [-0.031622777072899885, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [0.4683772229271001, 101, 38.5], onGround: true },
          'top speed 1.73 b/s': { tick: 7, pos: [0.09556481838903305, 101, 38.5], vel: [-0.04724078322880375, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [-0.003440559301562527, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_sprint_into_cows', {
    description: 'flat: forward+sprint 40 ticks, until still',
    steps: [press(['forward', 'sprint'], 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.0695604148553142, -0.0784000015258789, 0] },
          'top speed 6.7 b/s': { tick: 23, pos: [6.471719705724964, 101, 38.5], vel: [0.18291456144716547, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [11.640218933520485, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_stand_on_shulker', {
    description: 'flat: wait 20, forward 20 ticks, until still',
    steps: [ticks(20), press('forward', 20), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [2.5, 102, 38.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 2, pos: [2.5, 102, 38.5], onGround: true },
          'leaves the ground (2)': { tick: 26, pos: [3.5424309281337467, 101.92159999847412, 38.5], vel: [0.11473644494353707, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 30, pos: [4.122192377319905, 101, 38.5], onGround: true },
          'top speed 4.779 b/s': { tick: 31, pos: [4.361150310182702, 101, 38.5], vel: [0.13047104649764188, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [6.587505993940208, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_walk_across_boat', {
    description: 'flat: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 1, pos: [2.5980000033676625, 102, 38.5], vel: [0.053508008053839436, -0.0784000015258789, 0], onGround: false },
          'lands (1)': { tick: 4, pos: [2.8552130458209715, 101.5625, 38.5], onGround: true },
          'leaves the ground (2)': { tick: 9, pos: [3.8743595853726696, 101.48409999847412, 38.5], vel: [0.11646639332429318, -0.1552320045166016, 0], onGround: false },
          'lands (2)': { tick: 12, pos: [4.303958987191249, 101, 38.5], onGround: true },
          'top speed 4.692 b/s': { tick: 13, pos: [4.538561448816353, 101, 38.5], vel: [0.1280929589256399, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [8.486553322695753, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_walk_into_boat', {
    description: 'flat: forward 30 ticks, until still',
    steps: [press('forward', 30), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'peak height 0.563': { tick: 11, pos: [2.565182004898838, 101.5625, 38.5] },
          'leaves the ground (1)': { tick: 22, pos: [4.879243565714566, 101.48409999847412, 38.5], vel: [0.11782377223784907, -0.1552320045166016, 0], onGround: false },
          'lands (1)': { tick: 25, pos: [5.312559606836741, 101, 38.5], onGround: true },
          'top speed 4.713 b/s': { tick: 26, pos: [5.548184949935549, 101, 38.5], vel: [0.12865145227515334, -0.0784000015258789, 0] },
          'final state': { tick: 40, pos: [6.691208545380419, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_walk_through_cow', {
    description: 'flat: forward 40 ticks, until still',
    steps: [press('forward', 40), stopped(3)],
    groups: [
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0.053508008053839436, -0.0784000015258789, 0] },
          'top speed 5.443 b/s': { tick: 20, pos: [4.395364899208549, 101, 38.5], vel: [0.14858099335956726, -0.0784000015258789, 0] },
          'final state': { tick: 50, pos: [9.03606181944584, 101, 38.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
