// AUTO-GENERATED by physics-data-generator tools/gen-tests.mjs (working tree) from test/fixtures/java/*-recorded. Do not edit;
// change the catalog or tools/known-failures.json and regenerate.
/* eslint-env mocha */
const { recorded, press, server, ticks } = require('../../tools/java-harness')

describe('vanilla recordings: piston', () => {
  recorded('n_piston_push', {
    description: 'piston: server block, wait 30',
    steps: [server({ block: { at: [-2, 1, 0], state: 'redstone_block' } }), ticks(30)],
    groups: [
      {
        versions: ['1.11.2'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 2, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 5, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.12.2'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 2, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 4, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 7, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 16.2 b/s': { tick: 7, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 8, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19.2'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 3, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 4, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20', '1.20.4', '1.21.7'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 2, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 5, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.8', '1.21.9', '1.21.10'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 3, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 4, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 2, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 5, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.1'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 3, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 4, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.2'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 2, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 5, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.3'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, -0.0784000015258789, 0] },
          'leaves the ground (1)': { tick: 3, pos: [0.810000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: false },
          'top speed 10 b/s': { tick: 4, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 30, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })

  recorded('n_piston_push_jumping', {
    description: 'piston: jump 1 ticks, server block, wait 40',
    steps: [press('jump', 1), server({ block: { at: [-2, 1, 0], state: 'redstone_block' } }), ticks(40)],
    groups: [
      {
        versions: ['1.11.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.001': { tick: 3, pos: [0.5, 102.00133597911214, 2707.5] },
          'top speed 16.2 b/s': { tick: 4, pos: [1.310000011920929, 101.41999998688698, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 7, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.12.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 0.753': { tick: 2, pos: [0.810000011920929, 101.7531999805212, 2707.5] },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101.41999998688698, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 2707.5] },
          'top speed 16.2 b/s': { tick: 7, pos: [1.310000011920929, 101.41999998688698, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 10, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.19.2', '1.20'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 2707.5] },
          'lands (1)': { tick: 9, pos: [0.5, 102, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [0.5, 102, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.20.4', '1.21.8'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 0.753': { tick: 2, pos: [0.810000011920929, 101.7531999805212, 2707.5] },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101.41999998688698, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.9'],
        packetKnownFailure: 'pistons push the player after its own tick: vanilla sends the position from before the push',
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 0.753': { tick: 2, pos: [0.5, 101.7531999805212, 2707.5] },
          'top speed 10 b/s': { tick: 4, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 5, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.10'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 2707.5] },
          'lands (1)': { tick: 9, pos: [0.5, 102, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [0.5, 102, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['1.21.11'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'top speed 6.2 b/s': { tick: 2, pos: [0.810000011920929, 101.7531999805212, 2707.5], vel: [0, 0.24813599859094576, 0] },
          'peak height 1.001': { tick: 3, pos: [0.810000011920929, 102.00133597911214, 2707.5] },
          'lands (1)': { tick: 5, pos: [0.810000011920929, 101.375, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [0.810000011920929, 101.375, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.1'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 2707.5] },
          'lands (1)': { tick: 9, pos: [0.5, 102, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [0.5, 102, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.2'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 0.753': { tick: 2, pos: [0.810000011920929, 101.7531999805212, 2707.5] },
          'top speed 10 b/s': { tick: 3, pos: [1.310000011920929, 101.41999998688698, 2707.5], vel: [0, -0.0784000015258789, 0] },
          'lands (1)': { tick: 6, pos: [1.310000011920929, 101, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [1.310000011920929, 101, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      },
      {
        versions: ['26.3'],
        milestones: {
          'first tick': { tick: 1, vel: [0, 0.33319999363422365, 0] },
          'leaves the ground (1)': { tick: 1, pos: [0.5, 101.41999998688698, 2707.5], vel: [0, 0.33319999363422365, 0], onGround: false },
          'peak height 1.252': { tick: 6, pos: [0.5, 102.25220334025373, 2707.5] },
          'lands (1)': { tick: 9, pos: [0.5, 102, 2707.5], onGround: true },
          'final state': { tick: 41, pos: [0.5, 102, 2707.5], vel: [0, -0.0784000015258789, 0], onGround: true }
        }
      }
    ]
  })
})
